export type SupportedLanguage = "None" | "Spanish" | "Chinese" | "French" | "Japanese" | "Portuguese" | "Arabic" | "Vietnamese" | "Tagalog" | "Hindi" | "Korean";

export interface Translations {
  appName: string;
  appSubtitle: string;
  badgeText: string;
  navPrompts: string;
  navQuestionnaire: string;
  navChecklist: string;
  navTranslator: string;
  navFlutter: string;
  navHelp?: string;
  
  // Tab 1: Prompts
  promptsBannerTag: string;
  promptsBannerTitle: string;
  promptsBannerDesc: string;
  promptsCategoryTitle: string;
  promptsCategoryObjectives: string;
  promptsExplainToClient: string;
  promptsCopyBtn: string;
  promptsCopiedBtn: string;
  promptsOnboardingTipTitle: string;
  promptsOnboardingTipDesc: string;

  // Tab 2: Questionnaire
  questBannerTag: string;
  questBannerTitle: string;
  questBannerDesc: string;
  questQuickPresets: string;
  questFormTitle: string;
  questQ1: string;
  questQ2: string;
  questQ3: string;
  questQ4: string;
  questQ5: string;
  questSubmitBtn: string;
  questBriefTitle: string;
  questBriefObjective: string;
  questBriefTargetUsers: string;
  questBriefTimeline: string;
  questBriefMvpTitle: string;
  questBriefTechTitle: string;
  questBriefCopy: string;
  questBriefCopied: string;
  questBriefShareEmail: string;
  questBriefExportPdf: string;
  questBriefReadyTitle: string;
  questBriefReadyDesc: string;

  // Tab 3: Milestones Checklist
  milestonesBannerTag: string;
  milestonesBannerTitle: string;
  milestonesBannerDesc: string;
  milestonesResetBtn: string;
  milestonesPhase: string;
  milestonesAddNotePlaceholder: string;
  milestonesSaveIndicator: string;

  // Tab 4: Layman Translator
  transBannerTag: string;
  transBannerTitle: string;
  transBannerDesc: string;
  transInputLabel: string;
  transInputPlaceholder: string;
  transClickExample: string;
  transSelectLangLabel: string;
  transEnglishLevelLabel: string;
  transLevelSimple: string;
  transLevelMedium: string;
  transSubmitBtnThinking: string;
  transSubmitBtnReady: string;
  transStateReadyTitle: string;
  transStateReadyDesc: string;
  transStateThinkingTitle: string;
  transStateThinkingDesc: string;
  transOutputPlainWords: string;
  transOutputAnalogyStory: string;
  transOutputHowItMaps: string;
  transOutputKeyTakeaways: string;
  transOutputInYourLanguage: string;
  transOutputCopyBtn: string;
  transOutputCopiedBtn: string;

  // Tab 5: Flutter Bridge
  flutterBannerTag: string;
  flutterBannerSub: string;
  flutterBannerTitle: string;
  flutterBannerDesc: string;
  flutterSelectModule: string;
  flutterChecklistTitle: string;
  flutterChecklist1Title: string;
  flutterChecklist1Desc: string;
  flutterChecklist2Title: string;
  flutterChecklist2Desc: string;
  flutterChecklist3Title: string;
  flutterChecklist3Desc: string;
  flutterChecklist4Title: string;
  flutterChecklist4Desc: string;
  flutterCopyLibrary: string;
  flutterCopiedLibrary: string;

  // Global UI Interface selector
  interfaceLanguageSelector: string;
  footerRights: string;
}

export const LOCALIZATION_DICTIONARY: Record<SupportedLanguage, Translations> = {
  None: {
    appName: "Client Scoping Companion",
    appSubtitle: "Onboard founders, define clear MVPs, and translate tech jargon into friendly analogies!",
    badgeText: "Studio Guide",
    navPrompts: "💬 Kickstart Prompts",
    navQuestionnaire: "📝 Questionnaire & Brief",
    navChecklist: "📋 Alignment Checklist",
    navTranslator: "🌎 Layman Translator",
    navFlutter: "📱 Flutter & Stitch Dev",
    navHelp: "❓ SDLC Founder Help",
    
    promptsBannerTag: "🗣️ MEETING LAUNCHER",
    promptsBannerTitle: "Client Discussion Kickstarters",
    promptsBannerDesc: "When discussing custom software with a new client, dry questions like \"What database architecture do you prefer?\" cause panic and confusion. Use these warm, analogy-driven prompt cards to trigger brilliant client answers while keeping things delightfully simple!",
    promptsCategoryTitle: "Ready-to-use prompts for this alignment session",
    promptsCategoryObjectives: "🔑 Session Objectives:",
    promptsExplainToClient: "HOW TO EXPLAIN SIMPLY TO CLIENTS:",
    promptsCopyBtn: "Copy Question Template",
    promptsCopiedBtn: "Question Copied!",
    promptsOnboardingTipTitle: "Onboarding Tip for Non-Native Clients:",
    promptsOnboardingTipDesc: "If your client has difficulty speaking English, let them write or answer in their native tongue! You can paste their foreign language answers directly into the Founders Questionnaire or the Layman Translator, and let our Companion translate and summarize them perfectly into clean scoping guidelines.",

    questBannerTag: "📝 SCOPING QUESTIONNAIRE",
    questBannerTitle: "The 5-Question Founders Scoping Board",
    questBannerDesc: "Rather than writing endless pages of technical specifications, answer these 5 simple questions to get to the absolute heart of the project. Fill them in together with your client, or select a template to see how the software automatically prepares an easy-to-read scoping brief.",
    questQuickPresets: "⚡ Quick Presets (Click to load sample client answers):",
    questFormTitle: "✍️ The Five Basic Questions",
    questQ1: "1. Core Goal (What does the software do in 1 sentence?)",
    questQ2: "2. Target Audience (Who will use this, and when?)",
    questQ3: "3. MVP Scope (What are the top 3 'must-have' features?)",
    questQ4: "4. Technical Necessities (Do they need login, payments, or uploads?)",
    questQ5: "5. Budget & Timeline Constraints (When is launch & what is the approximate budget?)",
    questSubmitBtn: "Generate Client Scoping Brief ✨",
    questBriefTitle: "Project Scoping Brief",
    questBriefObjective: "🎯 Core Objective:",
    questBriefTargetUsers: "👥 Target Users:",
    questBriefTimeline: "💰 Constraints & Timeline:",
    questBriefMvpTitle: "🚀 MVP Launch Scope (Must-Haves):",
    questBriefTechTitle: "🛠️ Suggested Simple Tech Stack:",
    questBriefCopy: "Copy Brief to Clipboard",
    questBriefCopied: "Copy Brief Copied!",
    questBriefShareEmail: "Share via Email",
    questBriefExportPdf: "Export as PDF",
    questBriefReadyTitle: "Scoping Brief Ready to Build",
    questBriefReadyDesc: "Complete the 5 questions on the left or select an interactive preset template to instantly render a client-friendly project overview.",

    milestonesBannerTag: "📋 SYSTEM MILESTONES",
    milestonesBannerTitle: "Software Development Client Milestones",
    milestonesBannerDesc: "Avoid misunderstandings with clients and founders by using this step-by-step checklist. Check off completed alignments, type specific notes directly on each item, and save your progress! Notes are stored locally inside your browser.",
    milestonesResetBtn: "Reset All Checklists",
    milestonesPhase: "Phase",
    milestonesAddNotePlaceholder: "Type discussion details, decisions, or client comments here...",
    milestonesSaveIndicator: "✔ Note saved locally!",

    transBannerTag: "🗣️ MULTILINGUAL ASSISTANT",
    transBannerTitle: "The Jargon & Acronym Simplifier",
    transBannerDesc: "Do you hear complicated terms like \"Autonomous Execution\" or \"Retrieval-Augmented Generation\" and feel confused? Type them below! Our Smart Buddy will translate them and explain them using simple daily analogies so you can understand perfectly.",
    transInputLabel: "1. Type or paste the scary tech term:",
    transInputPlaceholder: "Example: Autonomous multi-agent orchestration, function calling, API integration...",
    transClickExample: "Or click an example:",
    transSelectLangLabel: "2. Translate explanation to your language:",
    transEnglishLevelLabel: "3. Target English Simplicity:",
    transLevelSimple: "Very Simple (A2 Level)",
    transLevelMedium: "Medium (B1 Level)",
    transSubmitBtnThinking: "Buddy is thinking...",
    transSubmitBtnReady: "Simplify & Explain! ✨",
    transStateReadyTitle: "Ready to Explain",
    transStateReadyDesc: "Type any digital technology or AI term on the left, select your language, and click \"Simplify\" to see an easy visual guide with friendly analogies!",
    transStateThinkingTitle: "Connecting with Smart Buddy...",
    transStateThinkingDesc: "Translating scary algorithms into normal everyday words.",
    transOutputPlainWords: "In Simple Words:",
    transOutputAnalogyStory: "Analogy Story",
    transOutputHowItMaps: "How it maps back to tech:",
    transOutputKeyTakeaways: "Key Takeaways to Remember:",
    transOutputInYourLanguage: "In your language",
    transOutputCopyBtn: "Copy Explainer text for client chat",
    transOutputCopiedBtn: "Explainer Copied!",

    flutterBannerTag: "📱 TRANSITION HUB",
    flutterBannerSub: "Antigravity & Stitch",
    flutterBannerTitle: "Flutter & Stitch Mobile Bridge",
    flutterBannerDesc: "Exporting your layouts to Antigravity and building high-fidelity native apps with Flutter has never been easier. Below are fully generated Dart libraries, data objects, styling guides, and HTTP network protocols mapped exactly to this companion app's business rules and design system!",
    flutterSelectModule: "📁 Select Export Module:",
    flutterChecklistTitle: "Stitch & Flutter Checklist",
    flutterChecklist1Title: "Stitch Border-Shadows:",
    flutterChecklist1Desc: "Use the provided neoBrutalistDecoration method in Flutter to recreate the retro flat shadow look cleanly on mobile.",
    flutterChecklist2Title: "Local Storage Persistence:",
    flutterChecklist2Desc: "Map our browser localStorage logic directly to Flutter's shared_preferences or Hive database to persist milestone checklists.",
    flutterChecklist3Title: "Sound Effect Synths:",
    flutterChecklist3Desc: "Use the soundpool Flutter plugin to play low-latency beep tones matching our Web Audio API synthetic triggers.",
    flutterChecklist4Title: "API Network Endpoint:",
    flutterChecklist4Desc: "Host our Express server on Cloud Run or a dedicated URL, configure CORS, and let the Flutter app consume the translated explanations.",
    flutterCopyLibrary: "Copy Full Library",
    flutterCopiedLibrary: "Dart Code Copied!",

    interfaceLanguageSelector: "🌎 Global App Language:",
    footerRights: "Client Scoping Companion • Crafted in the Vibrant Palette layout for Software Builders."
  },
  Spanish: {
    appName: "Compañero de Alcance del Cliente",
    appSubtitle: "¡Incorpora fundadores, define MVPs claros y traduce jerga tecnológica en analogías amigables!",
    badgeText: "Guía del Estudio",
    navPrompts: "💬 Preguntas Iniciales",
    navQuestionnaire: "📝 Cuestionario y Resumen",
    navChecklist: "📋 Lista de Alineación",
    navTranslator: "🌎 Traductor Simple",
    navFlutter: "📱 Desarrollo Flutter y Stitch",
    
    promptsBannerTag: "🗣️ LANZADOR DE REUNIONES",
    promptsBannerTitle: "Iniciadores de Discusión con Clientes",
    promptsBannerDesc: "Al hablar de software personalizado con un cliente nuevo, preguntas secas como \"¿Qué arquitectura de base de datos prefieres?\" causan pánico y confusión. ¡Usa estas tarjetas de preguntas amigables y guiadas por analogías para obtener respuestas brillantes de tus clientes mientras mantienes todo maravillosamente simple!",
    promptsCategoryTitle: "Preguntas listas para usar en esta sesión de alineación",
    promptsCategoryObjectives: "🔑 Objetivos de la Sesión:",
    promptsExplainToClient: "CÓMO EXPLICAR SENSÍBLEMENTE A LOS CLIENTES:",
    promptsCopyBtn: "Copiar Plantilla de Pregunta",
    promptsCopiedBtn: "¡Pregunta Copiada!",
    promptsOnboardingTipTitle: "Consejo de Onboarding para Clientes no Nativos:",
    promptsOnboardingTipDesc: "Si a su cliente le cuesta hablar en inglés, ¡permítale escribir o responder en su propio idioma! Puede pegar sus respuestas en otro idioma directamente en el Cuestionario para Fundadores o en el Traductor, y nuestro Compañero las traducirá y resumirá perfectamente en directrices claras.",

    questBannerTag: "📝 CUESTIONARIO DE ALCANCE",
    questBannerTitle: "El Tablero de Alcance de 5 Preguntas para Fundadores",
    questBannerDesc: "En lugar de escribir infinitas páginas de especificaciones técnicas, responda estas 5 preguntas simples para llegar al corazón absoluto del proyecto. Llénelas junto con su cliente, o elija una plantilla de ejemplo para ver cómo el sistema prepara automáticamente un resumen claro.",
    questQuickPresets: "⚡ Ajustes Rápidos (Haga clic para cargar respuestas de ejemplo):",
    questFormTitle: "✍️ Las Cinco Preguntas Básicas",
    questQ1: "1. Objetivo Principal (¿Qué hace el software en 1 frase?)",
    questQ2: "2. Audiencia Objetivo (¿Quién usará esto y cuándo?)",
    questQ3: "3. Alcance del MVP (¿Cuáles son las 3 características imprescindibles?)",
    questQ4: "4. Necesidades Técnicas (¿Necesitan inicio de sesión, pagos o cargas de archivos?)",
    questQ5: "5. Presupuesto y Tiempos (¿Cuándo es el lanzamiento y cuál es el presupuesto aproximado?)",
    questSubmitBtn: "Generar Resumen de Alcance del Cliente ✨",
    questBriefTitle: "Resumen del Alcance del Proyecto",
    questBriefObjective: "🎯 Objetivo Principal:",
    questBriefTargetUsers: "👥 Usuarios Objetivo:",
    questBriefTimeline: "💰 Restricciones y Tiempos:",
    questBriefMvpTitle: "🚀 Alcance del Lanzamiento MVP (Imprescindibles):",
    questBriefTechTitle: "🛠️ Stack Tecnológico Simple Sugerido:",
    questBriefCopy: "Copiar Resumen al Portapapeles",
    questBriefCopied: "¡Resumen Copiado!",
    questBriefShareEmail: "Compartir por Correo",
    questBriefExportPdf: "Exportar como PDF",
    questBriefReadyTitle: "Resumen de Alcance Listo para Crear",
    questBriefReadyDesc: "Complete las 5 preguntas a la izquierda o seleccione una plantilla interactiva para generar instantáneamente una vista general del proyecto amigable para el cliente.",

    milestonesBannerTag: "📋 HITOS DEL SISTEMA",
    milestonesBannerTitle: "Hitos para Clientes en el Desarrollo de Software",
    milestonesBannerDesc: "Evite malentendidos con clientes y fundadores usando esta lista de verificación paso a paso. ¡Marque los acuerdos completados, escriba notas específicas directamente en cada hito y guarde su progreso en su navegador de forma local!",
    milestonesResetBtn: "Restablecer Listas de Verificación",
    milestonesPhase: "Fase",
    milestonesAddNotePlaceholder: "Escriba detalles de la reunión, decisiones o comentarios del cliente aquí...",
    milestonesSaveIndicator: "✔ ¡Nota guardada localmente!",

    transBannerTag: "🗣️ ASISTENTE MULTILINGÜE",
    transBannerTitle: "El Simplificador de Jerga y Siglas",
    transBannerDesc: "¿Escucha términos complejos como \"Ejecución Autónoma\" o \"Generación Recuperada por Aumento (RAG)\" y se siente confundido? ¡Escríbalos abajo! Nuestro Smart Buddy los traducirá y explicará usando analogías cotidianas para que lo entienda a la perfección.",
    transInputLabel: "1. Escriba o pegue el término técnico complejo:",
    transInputPlaceholder: "Ejemplo: Llamada a funciones de agentes autónomos, integración de APIs...",
    transClickExample: "O haga clic en un ejemplo:",
    transSelectLangLabel: "2. Traducir la explicación a su idioma:",
    transEnglishLevelLabel: "3. Simplicidad del Inglés Objetivo:",
    transLevelSimple: "Muy Simple (Nivel A2)",
    transLevelMedium: "Medio (Nivel B1)",
    transSubmitBtnThinking: "El Buddy está pensando...",
    transSubmitBtnReady: "¡Simplificar y Explicar! ✨",
    transStateReadyTitle: "Listo para Explicar",
    transStateReadyDesc: "Escriba cualquier término de IA o tecnología a la izquierda, seleccione su idioma y haga clic en \"Simplificar\" para ver una guía visual fácil con analogías amigables.",
    transStateThinkingTitle: "Conectando con Smart Buddy...",
    transStateThinkingDesc: "Traduciendo algoritmos complejos a palabras normales y cotidianas.",
    transOutputPlainWords: "En Palabras Simples:",
    transOutputAnalogyStory: "Historia de Analogía",
    transOutputHowItMaps: "Cómo se conecta de vuelta con la tecnología:",
    transOutputKeyTakeaways: "Puntos Clave para Recordar:",
    transOutputInYourLanguage: "En tu idioma",
    transOutputCopyBtn: "Copiar texto explicativo para chat con el cliente",
    transOutputCopiedBtn: "¡Explicación Copiada!",

    flutterBannerTag: "📱 CENTRO DE TRANSICIÓN",
    flutterBannerSub: "Antigravity y Stitch",
    flutterBannerTitle: "Puente Móvil Flutter y Stitch",
    flutterBannerDesc: "Exportar sus diseños a Antigravity y crear aplicaciones nativas de alta fidelidad con Flutter nunca ha sido tan fácil. ¡A continuación se presentan librerías en Dart, objetos de datos, guías de estilo y protocolos de red HTTP generados exactamente con las reglas de negocio y diseño de esta aplicación!",
    flutterSelectModule: "📁 Seleccionar Módulo de Exportación:",
    flutterChecklistTitle: "Lista de Verificación Stitch y Flutter",
    flutterChecklist1Title: "Bordes y Sombras Stitch:",
    flutterChecklist1Desc: "Use el método neoBrutalistDecoration provisto en Flutter para recrear el look retro de sombras planas de manera limpia en móviles.",
    flutterChecklist2Title: "Persistencia de Almacenamiento Local:",
    flutterChecklist2Desc: "Asocie nuestra lógica de localStorage directamente a shared_preferences o base de datos Hive en Flutter para guardar el progreso.",
    flutterChecklist3Title: "Efectos de Sonido Sintéticos:",
    flutterChecklist3Desc: "Use el plugin soundpool de Flutter para reproducir los pitidos con baja latencia, imitando la API de audio web.",
    flutterChecklist4Title: "Endpoint de Red API:",
    flutterChecklist4Desc: "Aloje nuestro servidor Express en Cloud Run o una URL dedicada, configure CORS, y consuma las explicaciones traducidas desde Flutter.",
    flutterCopyLibrary: "Copiar Librería Completa",
    flutterCopiedLibrary: "¡Código de Dart Copiado!",

    interfaceLanguageSelector: "🌎 Idioma Global de la App:",
    footerRights: "Compañero de Alcance del Cliente • Creado con el diseño de Paleta Vibrante para Desarrolladores."
  },
  Chinese: {
    appName: "客户项目规划助手",
    appSubtitle: "高效对接创始人、明确MVP功能，并用通俗易懂的生活类比解释复杂的技术术语！",
    badgeText: "开发工作指南",
    navPrompts: "💬 沟通引导问题",
    navQuestionnaire: "📝 问卷与项目简报",
    navChecklist: "📋 进度对齐清单",
    navTranslator: "🌎 技术术语翻译器",
    navFlutter: "📱 Flutter & Stitch 迁移",
    
    promptsBannerTag: "🗣️ 会议启动器",
    promptsBannerTitle: "客户沟通引导话术",
    promptsBannerDesc: "在与非技术背景的客户讨论软件时，诸如“您首选什么数据库架构？”之类干燥枯燥的问题往往令人恐慌和困惑。使用这些温馨的、通过生活类比驱动的问题卡，可以轻松启发客户精彩的回答，同时保持交流的极致简单！",
    promptsCategoryTitle: "本阶段对齐会议现成可用的引导术语",
    promptsCategoryObjectives: "🔑 阶段讨论目标：",
    promptsExplainToClient: "如何向客户进行通俗易懂的解释：",
    promptsCopyBtn: "复制问题模板",
    promptsCopiedBtn: "问题已复制！",
    promptsOnboardingTipTitle: "非英语母语客户对接技巧：",
    promptsOnboardingTipDesc: "如果您的客户觉得用英语交流有困难，可以让其直接用母语书写或回答！您可以将他们的母语回答直接粘贴到“创始人问卷”或“术语翻译器”中，让本助手自动翻译并提炼成规范的项目规划要求。",

    questBannerTag: "📝 范围确立问卷",
    questBannerTitle: "创始人项目范围 5 问看板",
    questBannerDesc: "无需撰写动辄数十页的繁琐技术规格说明书，只需回答这 5 个简单的问题，就能精准捕获项目的核心价值。您可以与客户一同填写，或选择快捷预设模板，查看系统如何自动整理出简单易读的项目简报。",
    questQuickPresets: "⚡ 快捷预设（点击载入客户回答样例）：",
    questFormTitle: "✍️ 核心 5 问表单",
    questQ1: "1. 核心目标（用一句话说明该软件的作用是什么？）",
    questQ2: "2. 目标受众（谁会在什么场景下使用这款软件？）",
    questQ3: "3. MVP 范围（最核心、必须具备的前 3 项功能是什么？）",
    questQ4: "4. 技术必要条件（是否需要登录系统、在线支付或文件上传？）",
    questQ5: "5. 预算与时间限制（期望何时上线，约莫预算是多少？）",
    questSubmitBtn: "立即生成项目范围规划简报 ✨",
    questBriefTitle: "项目范围规划简报",
    questBriefObjective: "🎯 核心目标：",
    questBriefTargetUsers: "👥 目标受众：",
    questBriefTimeline: "💰 约束与时间线：",
    questBriefMvpTitle: "🚀 MVP 首发版本范围 (核心必备项):",
    questBriefTechTitle: "🛠️ 建议使用的简易技术栈 (通俗类比解释):",
    questBriefCopy: "复制简报到剪贴板",
    questBriefCopied: "简报复制成功！",
    questBriefShareEmail: "通过邮件分享",
    questBriefExportPdf: "导出为 PDF",
    questBriefReadyTitle: "简报生成器已就绪",
    questBriefReadyDesc: "在左侧填写 5 个核心问题，或选择一个交互式预设模板，即可立刻为客户呈现清晰友好的项目规划视图。",

    milestonesBannerTag: "📋 系统里程碑",
    milestonesBannerTitle: "软件开发客户里程碑清单",
    milestonesBannerDesc: "借助这份清晰的步骤清单，有效避免与客户及创始人之间的任何沟通误解。勾选已确认的事项，直接在每项条目下录入具体讨论备注，所有记录均会自动保存在您的浏览器本地！",
    milestonesResetBtn: "重置所有清单",
    milestonesPhase: "阶段",
    milestonesAddNotePlaceholder: "在此处记录讨论细节、会议决定或客户反馈意见...",
    milestonesSaveIndicator: "✔ 笔记已自动保存至本地！",

    transBannerTag: "🗣️ 多语言技术助手",
    transBannerTitle: "专业技术术语与缩写极简器",
    transBannerDesc: "面对“自主代理执行 (Autonomous Execution)”或“检索增强生成 (RAG)”等晦涩的名词时常感到头大？直接输入它们！我们的智能助手将为其配上最贴切的日常生活场景类比，并将其翻译成您的母语，帮您轻松秒懂！",
    transInputLabel: "1. 请输入或粘贴令人头疼的技术术语：",
    transInputPlaceholder: "例如: 智能体函数调用 (Function Calling), 接口对接, 自动流水线...",
    transClickExample: "或者点击下方样例直接体验：",
    transSelectLangLabel: "2. 将解析好的内容翻译成您的语言：",
    transEnglishLevelLabel: "3. 目标英语简单程度：",
    transLevelSimple: "极度简单 (A2 水平)",
    transLevelMedium: "中等易懂 (B1 水平)",
    transSubmitBtnThinking: "助手正在深度思考中...",
    transSubmitBtnReady: "极简转换并解释！✨",
    transStateReadyTitle: "技术解释器已就绪",
    transStateReadyDesc: "在左侧输入任何数字技术或AI术语，选择目标语言后点击“极简转换”，即可获得最生动、配有生活场景类比的通俗解析！",
    transStateThinkingTitle: "正在连接智能助手...",
    transStateThinkingDesc: "正在将晦涩难懂的算法逻辑转化为平易近人的生活常识。",
    transOutputPlainWords: "通俗白话解释：",
    transOutputAnalogyStory: "生活场景类比故事",
    transOutputHowItMaps: "如何对应到真实技术原理：",
    transOutputKeyTakeaways: "核心关键要点：",
    transOutputInYourLanguage: "您的母语对照",
    transOutputCopyBtn: "复制此通俗解析（方便发给客户讨论）",
    transOutputCopiedBtn: "解析内容已成功复制！",

    flutterBannerTag: "📱 移动端迁移枢纽",
    flutterBannerSub: "Antigravity & Stitch 设计",
    flutterBannerTitle: "Flutter & Stitch 移动端一键迁移",
    flutterBannerDesc: "将您的项目原型导出至 Antigravity 平台，并使用 Flutter 和 Stitch 设计指南构建高保真原生应用。下方已经为您完全准备好了符合本应用业务逻辑与设计系统规范的 Dart 实体类、数据定义、Stitch 主题样式及网络 API 通讯协议！",
    flutterSelectModule: "📁 选择导出的代码模块：",
    flutterChecklistTitle: "Stitch & Flutter 落地清单",
    flutterChecklist1Title: "Stitch 粗黑边框阴影效果:",
    flutterChecklist1Desc: "在 Flutter 中使用我们为您准备的 neoBrutalistDecoration 装饰器方法，即可在手机屏幕上完美还原标志性的扁平复古厚重阴影质感。",
    flutterChecklist2Title: "本地存储持久化实现:",
    flutterChecklist2Desc: "将网页端 localStorage 本地笔记逻辑映射至 Flutter 的 shared_preferences 或 Hive 轻量级数据库，确保离线清单进度不丢失。",
    flutterChecklist3Title: "点击微交互音效合成:",
    flutterChecklist3Desc: "在 Flutter 中集成 soundpool 插件，播放低延迟的合成蜂鸣器音效，完美还原 Web Audio API 的感官反馈。",
    flutterChecklist4Title: "API 服务部署与请求对接:",
    flutterChecklist4Desc: "将我们的 Express 后台服务部署在 Cloud Run 上，开启 CORS 跨域权限，便可让移动客户端流畅发起翻译及术语精炼请求。",
    flutterCopyLibrary: "一键复制完整代码库",
    flutterCopiedLibrary: "Dart 代码复制成功！",

    interfaceLanguageSelector: "🌎 全局界面语言:",
    footerRights: "客户项目规划助手 • 采用适合软件出海团队的 Vibrants 扁平拟物风格精心设计。"
  },
  French: {
    appName: "Compagnon de Cadrage Client",
    appSubtitle: "Incorporez des fondateurs, définissez des MVP clairs et traduisez le jargon technique en analogies simples !",
    badgeText: "Guide du Studio",
    navPrompts: "💬 Questions de Lancement",
    navQuestionnaire: "📝 Questionnaire & Brief",
    navChecklist: "📋 Liste d'Alignement",
    navTranslator: "🌎 Traducteur Layman",
    navFlutter: "📱 Flutter & Stitch Dev",
    
    promptsBannerTag: "🗣️ LANCEUR DE RÉUNION",
    promptsBannerTitle: "Questions de Discussion Clientes",
    promptsBannerDesc: "Lors de la discussion de logiciels sur mesure avec un nouveau client, des questions sèches comme « Quelle architecture de base de données préférez-vous ? » provoquent panique et confusion. Utilisez ces cartes d'incitation basées sur des analogies familières pour susciter de brillantes réponses de vos clients de manière très simple !",
    promptsCategoryTitle: "Questions prêtes à l'emploi pour cette session d'alignement",
    promptsCategoryObjectives: "🔑 Objectifs de la Session :",
    promptsExplainToClient: "COMMENT EXPLIQUER SIMPLEMENT AUX CLIENTS :",
    promptsCopyBtn: "Copier le Modèle de Question",
    promptsCopiedBtn: "Question Copiée !",
    promptsOnboardingTipTitle: "Conseil pour les Clients Non Natifs :",
    promptsOnboardingTipDesc: "Si votre client a du mal à s'exprimer en anglais, laissez-le écrire ou répondre dans sa langue maternelle ! Vous pouvez coller directement ses réponses dans le Questionnaire ou le Traducteur, et notre Compagnon s'occupera de traduire et de synthétiser le tout en spécifications claires.",

    questBannerTag: "📝 QUESTIONNAIRE DE CADRAGE",
    questBannerTitle: "Le Tableau de Cadrage en 5 Questions pour les Fondateurs",
    questBannerDesc: "Plutôt que de rédiger d'interminables pages de spécifications techniques, répondez à ces 5 questions simples pour aller au cœur du projet. Remplissez-les avec votre client ou sélectionnez un modèle pour voir comment le système génère automatiquement un brief clair.",
    questQuickPresets: "⚡ Raccourcis (Cliquez pour charger des exemples de réponses client) :",
    questFormTitle: "✍️ Les Cinq Questions de Base",
    questQ1: "1. Objectif Principal (Que fait le logiciel en 1 phrase ?)",
    questQ2: "2. Public Cible (Qui utilisera cela et quand ?)",
    questQ3: "3. Périmètre MVP (Quelles sont les 3 fonctionnalités indispensables ?)",
    questQ4: "4. Nécessités Techniques (Ont-ils besoin de connexion, de paiements ou de téléchargements ?)",
    questQ5: "5. Budget & Calendrier (Quand est prévu le lancement et quel est le budget approximatif ?)",
    questSubmitBtn: "Générer le Brief de Cadrage Client ✨",
    questBriefTitle: "Brief de Cadrage du Projet",
    questBriefObjective: "🎯 Objectif Principal :",
    questBriefTargetUsers: "👥 Utilisateurs Cibles :",
    questBriefTimeline: "💰 Limites & Calendrier :",
    questBriefMvpTitle: "🚀 Périmètre de Lancement MVP (Indispensables) :",
    questBriefTechTitle: "🛠️ Stack Technique Simple Suggérée :",
    questBriefCopy: "Copier le Brief dans le Presse-papiers",
    questBriefCopied: "Brief Copié !",
    questBriefShareEmail: "Partager par E-mail",
    questBriefExportPdf: "Exporter en PDF",
    questBriefReadyTitle: "Brief de Cadrage Prêt à Créer",
    questBriefReadyDesc: "Remplissez les 5 questions à gauche ou sélectionnez un modèle interactif pour générer instantanément une vue d'ensemble du projet adaptée au client.",

    milestonesBannerTag: "📋 JALONS DU SYSTÈME",
    milestonesBannerTitle: "Jalons Clients pour le Développement Logiciel",
    milestonesBannerDesc: "Évitez les malentendus avec les clients et les fondateurs en utilisant cette liste de contrôle étape par étape. Cochez les accords validés, saisissez des notes directement sur chaque élément et sauvegardez votre progression localement dans votre navigateur !",
    milestonesResetBtn: "Réinitialiser les Listes de Contrôle",
    milestonesPhase: "Phase",
    milestonesAddNotePlaceholder: "Saisissez les détails de la réunion, les décisions ou les commentaires du client ici...",
    milestonesSaveIndicator: "✔ Note enregistrée localement !",

    transBannerTag: "🗣️ ASSISTANT MULTILINGUE",
    transBannerTitle: "Le Simplificateur de Jargon et d'Acronymes",
    transBannerDesc: "Entendez-vous des termes complexes comme « Exécution Autonome » ou « Génération Augmentée de Récupération (RAG) » et vous vous sentez perdu ? Saisissez-les ci-dessous ! Notre Smart Buddy les traduira et les expliquera avec des analogies du quotidien pour vous aider à comprendre parfaitement.",
    transInputLabel: "1. Saisissez ou collez le terme technique complexe :",
    transInputPlaceholder: "Exemple : Appel de fonctions d'agents autonomes, intégration d'API...",
    transClickExample: "Ou cliquez sur un exemple :",
    transSelectLangLabel: "2. Traduire l'explication dans votre langue :",
    transEnglishLevelLabel: "3. Niveau de Simplicité de l'Anglais :",
    transLevelSimple: "Très Simple (Niveau A2)",
    transLevelMedium: "Moyen (Niveau B1)",
    transSubmitBtnThinking: "Le Buddy réfléchit...",
    transSubmitBtnReady: "Simplifier & Expliquer ! ✨",
    transStateReadyTitle: "Prêt à Expliquer",
    transStateReadyDesc: "Saisissez n'importe quel terme de technologie ou d'IA à gauche, sélectionnez votre langue et cliquez sur \"Simplifier\" pour voir un guide visuel simple avec des analogies amicales !",
    transStateThinkingTitle: "Connexion avec Smart Buddy...",
    transStateThinkingDesc: "Traduction d'algorithmes complexes en mots simples du quotidien.",
    transOutputPlainWords: "En Mots Simples :",
    transOutputAnalogyStory: "Histoire d'Analogie",
    transOutputHowItMaps: "Lien avec le fonctionnement technique :",
    transOutputKeyTakeaways: "Points Clés à Retenir :",
    transOutputInYourLanguage: "Dans votre langue",
    transOutputCopyBtn: "Copier l'explication pour l'envoyer au client",
    transOutputCopiedBtn: "Explication Copiée !",

    flutterBannerTag: "📱 ENTRAIDE DE TRANSITION",
    flutterBannerSub: "Antigravity & Stitch",
    flutterBannerTitle: "Passerelle Mobile Flutter & Stitch",
    flutterBannerDesc: "Exporter vos maquettes vers Antigravity et créer des applications mobiles natives de haute fidélité avec Flutter n'a jamais été aussi simple. Retrouvez ci-dessous des librairies en Dart, des objets de données, des guides de style et des protocoles de réseau HTTP générés exactement selon les spécifications de cette application !",
    flutterSelectModule: "📁 Sélectionner le Module à Exporter :",
    flutterChecklistTitle: "Liste de Contrôle Stitch & Flutter",
    flutterChecklist1Title: "Bordures et Ombres Stitch :",
    flutterChecklist1Desc: "Utilisez la méthode neoBrutalistDecoration fournie en Flutter pour recréer l'aspect rétro d'ombres plates proprement sur mobile.",
    flutterChecklist2Title: "Persistance de Stockage Local :",
    flutterChecklist2Desc: "Associez notre logique de localStorage directement à shared_preferences ou base de données Hive en Flutter pour conserver la progression.",
    flutterChecklist3Title: "Effets Sonores Synthétiques :",
    flutterChecklist3Desc: "Utilisez le plugin soundpool de Flutter pour jouer des tonalités de bip à faible latence, imitant l'API Web Audio.",
    flutterChecklist4Title: "Endpoint Réseau de l'API :",
    flutterChecklist4Desc: "Hébergez notre serveur Express sur Cloud Run ou une URL dédiée, configurez le CORS, et laissez l'application Flutter consommer les explications simplifiées.",
    flutterCopyLibrary: "Copier la Librairie Complète",
    flutterCopiedLibrary: "Code Dart Copié !",

    interfaceLanguageSelector: "🌎 Langue Globale de l'App :",
    footerRights: "Compagnon de Cadrage Client • Conçu dans la charte graphique de la Palette Vibrante pour Développeurs."
  },
  Japanese: {
    appName: "顧客スコープ策定アシスタント",
    appSubtitle: "クライアントの要望を引き出し、MVPを明確に定義し、技術用語を日常の例え話にわかりやすく翻訳します！",
    badgeText: "スタジオ開発ガイド",
    navPrompts: "💬 対話用スターター質問",
    navQuestionnaire: "📝 簡易要件問診票",
    navChecklist: "📋 要件合意チェックリスト",
    navTranslator: "🌎 やさしいIT翻訳器",
    navFlutter: "📱 Flutter & Stitch 移行",
    
    promptsBannerTag: "🗣️ 会議起動ツール",
    promptsBannerTitle: "クライアント議論の呼び水質問カード",
    promptsBannerDesc: "非技術者のクライアントに「データベース設計はどうしますか？」などの無機質な質問を投げると、困惑や不安を招きます。日常の身近な例え話を用いた対話用質問カードを使うことで、難解な仕様をシンプルに解きほぐしながら、最適なアイデアを引き出せます！",
    promptsCategoryTitle: "この検討セッションですぐに使える呼び水質問一覧",
    promptsCategoryObjectives: "🔑 セッションの達成目標：",
    promptsExplainToClient: "クライアントに伝える「やさしい翻訳ガイド」：",
    promptsCopyBtn: "質問用テンプレートをコピー",
    promptsCopiedBtn: "コピーしました！",
    promptsOnboardingTipTitle: "英語圏以外のクライアントと対話する時のヒント：",
    promptsOnboardingTipDesc: "もしクライアントが英語で細かく説明するのが難しい場合は、ご自身の母国語で回答を書いてもらってください！その文章を「要件問診票」や「IT翻訳器」にそのまま貼り付けるだけで、本アシスタントが美しいシステム要件仕様に変換・整理します。",

    questBannerTag: "📝 要件スコープ問診",
    questBannerTitle: "創業者向け・要件定義の「基本5問」ボード",
    questBannerDesc: "何十ページもの分厚い技術仕様書をいきなり書く代わりに、この極めてシンプルな5つの質問に答えるだけで、プロジェクトの本質に迫れます。クライアントと一緒に回答するか、プリセット例を選択して、システムがどのように簡潔なプロジェクト要件書を自動生成するか確認してください。",
    questQuickPresets: "⚡ クイックプリセット（クリックでサンプル顧客回答をロードします）：",
    questFormTitle: "✍️ 核心に迫る5つの基本質問",
    questQ1: "1. 核心的なゴール（このアプリを一言で言うと何をするもの？）",
    questQ2: "2. ターゲット（誰がいつどのような場面で使うもの？）",
    questQ3: "3. MVPの範囲（最初に絶対に外せない上位3つの必須機能は？）",
    questQ4: "4. 技術的必要性（ログイン、クレジットカード決済、画像やファイルのアップロードは必要？）",
    questQ5: "5. 予算とスケジュールの制約（いつ頃のローンチを目指し、予算枠はどれくらい？）",
    questSubmitBtn: "プロジェクト要件書を自動生成する ✨",
    questBriefTitle: "プロジェクト要件スコープ簡報",
    questBriefObjective: "🎯 核心的ゴール：",
    questBriefTargetUsers: "👥 対象ターゲット：",
    questBriefTimeline: "💰 スケジュールと予算：",
    questBriefMvpTitle: "🚀 MVPローンチ時の機能範囲（必須要件）：",
    questBriefTechTitle: "🛠️ 推奨されるシンプルな技術スタック（例え話付き）：",
    questBriefCopy: "要件書をクリップボードにコピー",
    questBriefCopied: "要件書をコピーしました！",
    questBriefShareEmail: "メールで共有",
    questBriefExportPdf: "PDFとしてエクスポート",
    questBriefReadyTitle: "要件書生成の準備完了",
    questBriefReadyDesc: "左側の5つの質問に入力するか、インタラクティブなプリセット例を選択すると、クライアント向けの分かりやすい構成案が即座に生成されます。",

    milestonesBannerTag: "📋 システムマイルストーン",
    milestonesBannerTitle: "ソフトウェア開発におけるクライアント合意マイルストーン",
    milestonesBannerDesc: "ステップバイステップの合意チェックリストを活用し、開発段階ごとの誤解や言った言わないのトラブルを回避しましょう。合意済みの箇所にチェックを入れ、議論の詳細や決定事項、要望をそのままその場にメモしてください。メモはブラウザのローカル環境に自動保存されます！",
    milestonesResetBtn: "チェックリストをすべて初期化",
    milestonesPhase: "フェーズ",
    milestonesAddNotePlaceholder: "議論の詳細、決定事項、またはクライアントのコメントを入力...",
    milestonesSaveIndicator: "✔ メモをローカルに自動保存しました！",

    transBannerTag: "🗣️ 多言語ITアシスタント",
    transBannerTitle: "IT用語・略語の日常例え話翻訳器",
    transBannerDesc: "「自律型エージェント(Autonomous Execution)」や「RAG(検索拡張生成)」などの難解なIT用語に戸惑っていませんか？下にキーワードを入力してください！私たちのスマートエージェントが、分かりやすい日常のストーリー（例え話）に翻訳・解説します。",
    transInputLabel: "1. 難解な技術用語・カタカナ語を入力、または貼り付け：",
    transInputPlaceholder: "例：自律エージェントのファンクション呼び出し、API連携、非同期処理...",
    transClickExample: "または以下の例を直接クリック：",
    transSelectLangLabel: "2. 解説をあなたの母国語に翻訳する：",
    transEnglishLevelLabel: "3. 解説用英語のやさしさ度合い：",
    transLevelSimple: "とてもやさしい英語（A2レベル相当）",
    transLevelMedium: "中等度の英語（B1レベル相当）",
    transSubmitBtnThinking: "アシスタントが考え中...",
    transSubmitBtnReady: "分かりやすく解説する！✨",
    transStateReadyTitle: "技術用語翻訳の準備完了",
    transStateReadyDesc: "左側に難解なAIや技術用語を入力し、翻訳したい言語を選択して「解説する」をクリックすると、日常の例え話をふんだんに用いた分かりやすい構成で解説が生成されます。",
    transStateThinkingTitle: "スマートエージェントに接続中...",
    transStateThinkingDesc: "小難しいアルゴリズム用語を、親しみやすい言葉にほぐしています。",
    transOutputPlainWords: "一言で言うと（やさしい言葉）：",
    transOutputAnalogyStory: "日常ストーリーの例え話",
    transOutputHowItMaps: "実際の技術的な仕組みとの対応：",
    transOutputKeyTakeaways: "覚えておきたい重要なポイント：",
    transOutputInYourLanguage: "あなたの母国語での对照",
    transOutputCopyBtn: "この解説をコピーする（チャット等での説明に便利です）",
    transOutputCopiedBtn: "解説をコピーしました！",

    flutterBannerTag: "📱 モバイル移行ハブ",
    flutterBannerSub: "Antigravity & Stitch デザイン",
    flutterBannerTitle: "Flutter & Stitch モバイル版への移行ブリッジ",
    flutterBannerDesc: "プロトタイプをモバイル実機向けに Antigravity 開発プラットフォームへとエクスポートし、FlutterとStitchのデザイン仕様を用いて美しいネイティブアプリへと落とし込むのは非常にスムーズです。本アプリのビジネスルール、データ構造、テーマ設計に対応するDartクラスやAPI通信コードが完全に用意されています！",
    flutterSelectModule: "📁 エクスポートするコードモジュールを選択：",
    flutterChecklistTitle: "Stitch & Flutter 開発チェックリスト",
    flutterChecklist1Title: "Stitch 側の太いボーダー影効果:",
    flutterChecklist1Desc: "Flutter内に用意された <code>neoBrutalistDecoration</code> デコレーション関数を使うことで、特徴的なレトロ・ネオブルータリズム調の厚みある平らな影をモバイル画面でそのまま再現できます。",
    flutterChecklist2Title: "ローカル状態管理・永続化:",
    flutterChecklist2Desc: "ブラウザ側の localStorage でのメモ保存ロジックを、Flutter標準の <code>shared_preferences</code> や <code>Hive</code> データベースにそのままマッピングしてマイルストーンを永続化します。",
    flutterChecklist3Title: "マイクロインタラクション音響効果:",
    flutterChecklist3Desc: "Flutterで <code>soundpool</code> ライブラリを使用することで、ブラウザ標準の Web Audio API シンセサイザーと同様の低遅延な電子音フィードバックをモバイルで再現できます。",
    flutterChecklist4Title: "API 連携エンドポイントの設置:",
    flutterChecklist4Desc: "当Expressバックエンドを Cloud Run 等にホスティングし、CORS通信を許可。Flutterアプリから直接IT用語翻訳/解説APIを投げられるようにします。",
    flutterCopyLibrary: "コードライブラリをコピーする",
    flutterCopiedLibrary: "Dartコードをコピーしました！",

    interfaceLanguageSelector: "🌎 アプリ表示言語:",
    footerRights: "顧客スコープ策定アシスタント • クリエイター向けの鮮やかな「Vibrant Palette」フラットUIデザインで構築。"
  },
  Portuguese: {
    appName: "Companion de Escopo do Cliente",
    appSubtitle: "Integre fundadores, defina MVPs claros e traduza jargões técnicos em analogias amigáveis!",
    badgeText: "Guia do Estúdio",
    navPrompts: "💬 Perguntas de Partida",
    navQuestionnaire: "📝 Questionário e Resumo",
    navChecklist: "📋 Lista de Alinhamento",
    navTranslator: "🌎 Tradutor Layman",
    navFlutter: "📱 Desenvolvimento Flutter & Stitch",
    
    promptsBannerTag: "🗣️ INICIADOR DE REUNIÃO",
    promptsBannerTitle: "Iniciadores de Discussão com Clientes",
    promptsBannerDesc: "Ao discutir software customizado com um novo cliente, perguntas secas como \"Qual arquitetura de banco de dados você prefere?\" causam pânico e confusão. Use estes cartões amigáveis guiados por analogias para obter respostas brilhantes de seus clientes mantendo tudo maravilhosamente simples!",
    promptsCategoryTitle: "Perguntas prontas para usar nesta sessão de alinhamento",
    promptsCategoryObjectives: "🔑 Objetivos da Sessão:",
    promptsExplainToClient: "COMO EXPLICAR DE FORMA SIMPLES AOS CLIENTES:",
    promptsCopyBtn: "Copiar Modelo de Pergunta",
    promptsCopiedBtn: "Pergunta Copiada!",
    promptsOnboardingTipTitle: "Dica de Onboarding para Clientes Não Nativos:",
    promptsOnboardingTipDesc: "Se o seu cliente tem dificuldade em falar inglês, permita que ele escreva ou responda no seu próprio idioma! Você pode colar as respostas diretamente no Questionário ou no Tradutor, e nosso Companion fará a tradução e resumo ideais em diretrizes limpas.",

    questBannerTag: "📝 QUESTIONÁRIO DE ESCOPO",
    questBannerTitle: "O Painel de Escopo de 5 Perguntas para Fundadores",
    questBannerDesc: "Em vez de escrever infinitas páginas de especificações técnicas, responda a estas 5 perguntas simples para ir ao coração absoluto do projeto. Preencha-as junto com o cliente ou selecione um modelo para ver como o sistema prepara automaticamente um resumo claro.",
    questQuickPresets: "⚡ Atalhos Rápidos (Clique para carregar respostas de exemplo do cliente):",
    questFormTitle: "✍️ As Cinco Perguntas Básicas",
    questQ1: "1. Objetivo Principal (O que o software faz em 1 frase?)",
    questQ2: "2. Público-Alvo (Quem usará isto e quando?)",
    questQ3: "3. Escopo do MVP (Quais são os 3 recursos indispensáveis?)",
    questQ4: "4. Necessidades Técnicas (Eles precisam de login, pagamentos ou uploads de arquivos?)",
    questQ5: "5. Orçamento e Cronograma (Quando é o lançamento e qual o orçamento aproximado?)",
    questSubmitBtn: "Gerar Resumo do Escopo do Cliente ✨",
    questBriefTitle: "Resumo do Escopo do Projeto",
    questBriefObjective: "🎯 Objetivo Principal:",
    questBriefTargetUsers: "👥 Usuários-Alvo:",
    questBriefTimeline: "💰 Restrições e Cronograma:",
    questBriefMvpTitle: "🚀 Escopo do Lançamento MVP (Indispensáveis):",
    questBriefTechTitle: "🛠️ Stack Técnica Simples Sugerida:",
    questBriefCopy: "Copiar Resumo para a Área de Transferência",
    questBriefCopied: "Resumo Copiado!",
    questBriefShareEmail: "Compartilhar por E-mail",
    questBriefExportPdf: "Exportar como PDF",
    questBriefReadyTitle: "Resumo de Escopo Pronto para Construir",
    questBriefReadyDesc: "Preencha as 5 perguntas à esquerda ou selecione um modelo interativo para gerar instantaneamente uma visão geral amigável do projeto.",

    milestonesBannerTag: "📋 MARCOS DO SISTEMA",
    milestonesBannerTitle: "Marcos de Clientes para Desenvolvimento de Software",
    milestonesBannerDesc: "Evite desentendimentos com clientes e fundadores usando esta lista de verificação passo a passo. Marque os acordos validados, insira notas específicas diretamente em cada marco e salve o progresso localmente em seu navegador!",
    milestonesResetBtn: "Restaurar Listas de Verificação",
    milestonesPhase: "Fase",
    milestonesAddNotePlaceholder: "Digite detalhes da reunião, decisões ou comentários do cliente aqui...",
    milestonesSaveIndicator: "✔ Nota guardada localmente!",

    transBannerTag: "🗣️ ASSISTENTE MULTILÍNGUE",
    transBannerTitle: "O Simplificador de Jargões e Acrônimos",
    transBannerDesc: "Você ouve termos complexos como \"Execução Autônoma\" ou \"Geração Aumentada por Recuperação (RAG)\" e se sente confuso? Digite-os abaixo! Nosso Smart Buddy fará a tradução e explicação usando analogias do cotidiano para que você entenda à perfeição.",
    transInputLabel: "1. Digite ou cole o termo técnico complexo:",
    transInputPlaceholder: "Exemplo: Chamada de função de agentes autônomos, integração de APIs...",
    transClickExample: "Ou clique em um exemplo:",
    transSelectLangLabel: "2. Traduzir a explicação para seu idioma:",
    transEnglishLevelLabel: "3. Simplicidade do Inglês de Destino:",
    transLevelSimple: "Muito Simples (Nível A2)",
    transLevelMedium: "Médio (Nível B1)",
    transSubmitBtnThinking: "O Buddy está pensando...",
    transSubmitBtnReady: "Simplificar e Explicar! ✨",
    transStateReadyTitle: "Pronto para Explicar",
    transStateReadyDesc: "Digite qualquer termo de IA ou tecnologia à esquerda, selecione seu idioma e clique em \"Simplificar\" para ver um guia visual simples com analogias amigáveis.",
    transStateThinkingTitle: "Conectando com Smart Buddy...",
    transStateThinkingDesc: "Traduzindo algoritmos complexos em palavras cotidianas e normais.",
    transOutputPlainWords: "Em Palavras Simples:",
    transOutputAnalogyStory: "História de Analogia",
    transOutputHowItMaps: "Como se relaciona de volta com a tecnologia:",
    transOutputKeyTakeaways: "Pontos Importantes a Lembrar:",
    transOutputInYourLanguage: "Em seu idioma",
    transOutputCopyBtn: "Copiar texto de explicação para enviar ao cliente",
    transOutputCopiedBtn: "Explicação Copiada!",

    flutterBannerTag: "📱 HUB DE TRANSIÇÃO",
    flutterBannerSub: "Antigravity e Stitch",
    flutterBannerTitle: "Ponte Móvel Flutter e Stitch",
    flutterBannerDesc: "Exportar seus protótipos para a plataforma Antigravity e criar aplicativos nativos de alta fidelidade com Flutter e Stitch nunca foi tão simples. Encontre abaixo as bibliotecas em Dart, objetos de dados, guias de estilo e protocolos de rede HTTP gerados de acordo com os requisitos desta aplicação!",
    flutterSelectModule: "📁 Selecionar Módulo de Exportação:",
    flutterChecklistTitle: "Lista de Verificação Stitch & Flutter",
    flutterChecklist1Title: "Bordas e Sombras Stitch:",
    flutterChecklist1Desc: "Use o método neoBrutalistDecoration fornecido em Flutter para recriar o visual retro de sombras chapadas perfeitamente no celular.",
    flutterChecklist2Title: "Persistência no Armazenamento Local:",
    flutterChecklist2Desc: "Associe nossa lógica de localStorage diretamente a shared_preferences ou banco de dados Hive em Flutter para preservar o progresso.",
    flutterChecklist3Title: "Efeitos Sonoros Sintéticos:",
    flutterChecklist3Desc: "Use o plugin soundpool do Flutter para reproduzir bipagens eletrônicas de baixa latência imitando a API Web Audio.",
    flutterChecklist4Title: "Endpoint de Rede API:",
    flutterChecklist4Desc: "Aloje nosso servidor Express no Cloud Run ou uma URL dedicada, configure o CORS e consuma as explicações simplificadas do Flutter.",
    flutterCopyLibrary: "Copiar Biblioteca Completa",
    flutterCopiedLibrary: "Código Dart Copiado!",

    interfaceLanguageSelector: "🌎 Idioma Global do App:",
    footerRights: "Companion de Escopo do Cliente • Desenvolvido sob a paleta vibrante para criadores de software."
  },
  Arabic: {
    appName: "رفيق تحديد نطاق المشروع",
    appSubtitle: "ساعد المؤسسين في إطلاق مشاريعهم، وحدد أهداف MVP واضحة، وترجم المصطلحات التقنية المعقدة إلى تشبيهات يومية ودودة!",
    badgeText: "دليل الاستوديو",
    navPrompts: "💬 أسئلة إطلاق النقاش",
    navQuestionnaire: "📝 استبيان وموجز المشروع",
    navChecklist: "📋 قائمة التحقق والوفاق",
    navTranslator: "🌎 مترجم المصطلحات المبسط",
    navFlutter: "📱 تطوير فلاتر وستيتش",
    
    promptsBannerTag: "🗣️ منطلق الاجتماعات",
    promptsBannerTitle: "مفاتيح بدء الحوار مع العملاء",
    promptsBannerDesc: "عند مناقشة البرمجيات المخصصة مع عميل غير تقني، فإن الأسئلة الجافة مثل \"ما هي بنية قاعدة البيانات المفضلة لديك؟\" تسبب القلق والارتباك. استخدم بطاقات الحوار المستندة إلى التشبيهات اليومية للحصول على إجابات ذكية ورائعة من عملائك مع الحفاظ على البساطة المطلقة!",
    promptsCategoryTitle: "مفاتيح جاهزة للاستخدام في هذه الجلسة للوفاق والتوجيه",
    promptsCategoryObjectives: "🔑 أهداف الجلسة الرئيسية:",
    promptsExplainToClient: "كيفية الشرح بطريقة مبسطة للعملاء:",
    promptsCopyBtn: "نسخ قالب السؤال",
    promptsCopiedBtn: "تم نسخ السؤال!",
    promptsOnboardingTipTitle: "نصيحة لإطلاق النقاش مع العملاء غير الناطقين بالإنجليزية:",
    promptsOnboardingTipDesc: "إذا واجه عميلك صعوبة في التعبير باللغة الإنجليزية، دعه يكتب أو يجيب بلغته الأم! يمكنك لصق إجاباتهم مباشرة في الاستبيان أو المترجم، وسيقوم الرفيق بترجمتها وتلخيصها بدقة في مبادئ توجيهية واضحة لتحديد النطاق.",

    questBannerTag: "📝 استبيان تحديد النطاق",
    questBannerTitle: "لوحة تحديد النطاق للمؤسسين بـ 5 أسئلة أساسية",
    questBannerDesc: "بدلاً من كتابة صفحات لا حصر لها من المواصفات الفنية المعقدة، أجب عن هذه الأسئلة الخمسة البسيطة للوصول إلى جوهر المشروع. املأها مع عميلك، أو اختر نموذجاً تجريبياً لرؤية كيف يقوم النظام تلقائياً بإعداد موجز واضح وسهل القراءة.",
    questQuickPresets: "⚡ قوالب سريعة جاهزة (اضغط لتحميل إجابات عملاء عشوائية ومحاكاتها):",
    questFormTitle: "✍️ الأسئلة الخمسة الأساسية",
    questQ1: "1. الهدف الرئيسي (ماذا يفعل البرنامج في جملة واحدة مبسطة؟)",
    questQ2: "2. الجمهور المستهدف (من سيستخدم هذا ومتى؟)",
    questQ3: "3. نطاق MVP الأساسي (ما هي أهم 3 ميزات لا غنى عنها لإطلاق النسخة الأولى؟)",
    questQ4: "4. المتطلبات التقنية الضرورية (هل تحتاج إلى تسجيل دخول، دفع إلكتروني، أو رفع ملفات وصور؟)",
    questQ5: "5. الميزانية والجدول الزمني (متى تأمل الإطلاق وما هي الميزانية التقريبية؟)",
    questSubmitBtn: "توليد موجز تحديد النطاق للعميل ✨",
    questBriefTitle: "موجز نطاق المشروع المولد",
    questBriefObjective: "🎯 الهدف الرئيسي للمشروع:",
    questBriefTargetUsers: "👥 الجمهور المستهدف:",
    questBriefTimeline: "💰 القيود والجدول الزمني:",
    questBriefMvpTitle: "🚀 نطاق إطلاق النسخة الأولى MVP (الضروريات):",
    questBriefTechTitle: "🛠️ الهيكل التقني المقترح مع التشبيهات المبسطة:",
    questBriefCopy: "نسخ الموجز إلى الحافظة",
    questBriefCopied: "تم نسخ الموجز بنجاح!",
    questBriefShareEmail: "مشاركة عبر البريد الإلكتروني",
    questBriefExportPdf: "تصدير كملف PDF",
    questBriefReadyTitle: "الموجز جاهز للتوليد الآن",
    questBriefReadyDesc: "أكمل الإجابة عن الأسئلة الخمسة على اليسار أو اختر قالباً تفاعلياً جاهزاً لتقديم نظرة عامة واضحة ومبسطة للمشروع فوراً.",

    milestonesBannerTag: "📋 معالم تقدم النظام",
    milestonesBannerTitle: "معالم وقوائم التحقق لعملاء تطوير البرمجيات",
    milestonesBannerDesc: "تجنب سوء الفهم والمشاكل مع العملاء والمؤسسين من خلال استخدام قائمة التحقق خطوة بخطوة. حدد ما تم إنجازه، واكتب ملاحظاتك مباشرة على كل معلم، واحفظ تقدمك محلياً في المتصفح تلقائياً!",
    milestonesResetBtn: "إعادة تعيين كافة القوائم",
    milestonesPhase: "المرحلة",
    milestonesAddNotePlaceholder: "اكتب تفاصيل الاجتماع، القرارات، أو تعليقات العميل هنا...",
    milestonesSaveIndicator: "✔ تم حفظ الملاحظة محلياً بنجاح!",

    transBannerTag: "🗣️ مساعد ذكي متعدد اللغات",
    transBannerTitle: "مبسط المصطلحات والرموز التقنية",
    transBannerDesc: "هل تسمع مصطلحات معقدة مثل \"التنفيذ الذاتي\" أو \"الاسترجاع المعزز بالتوليد RAG\" وتشعر بالارتباك؟ اكتبها بالأسفل! وسيقوم مساعدنا الذكي بترجمتها وشرحها باستخدام تشبيهات يومية واضحة تفهمها بسهولة.",
    transInputLabel: "1. اكتب أو الصق المصطلح التقني المعقد هنا:",
    transInputPlaceholder: "مثال: استدعاء دالة العميل الذكي، ربط الواجهات البرمجية APIs...",
    transClickExample: "أو اختر مثالاً جاهزاً للتجربة السريعة:",
    transSelectLangLabel: "2. ترجمة الشرح المبسط إلى لغتك الأم:",
    transEnglishLevelLabel: "3. مستوى بساطة اللغة الإنجليزية المستهدفة:",
    transLevelSimple: "بسيط جداً (مستوى A2)",
    transLevelMedium: "متوسط الفهم (مستوى B1)",
    transSubmitBtnThinking: "المساعد يفكر الآن...",
    transSubmitBtnReady: "تبسيط الشرح وتوضيحه! ✨",
    transStateReadyTitle: "المترجم جاهز للشرح الآن",
    transStateReadyDesc: "اكتب أي مصطلح تقني أو ذكاء اصطناعي على اليسار، واختر لغتك، ثم اضغط \"تبسيط\" للحصول على دليل مرئي مشروح بتشبيهات ودودة وقريبة للفهم!",
    transStateThinkingTitle: "جاري الاتصال بالمساعد الذكي...",
    transStateThinkingDesc: "تفكيك الخوارزميات والرموز المعقدة إلى كلمات عادية وواضحة من واقع الحياة اليومية.",
    transOutputPlainWords: "بالكلمات البسيطة والموجزة:",
    transOutputAnalogyStory: "التشبيه والقصة اليومية",
    transOutputHowItMaps: "كيف يترجم هذا إلى الواقع البرمجي التقني:",
    transOutputKeyTakeaways: "النقاط الأساسية التي يجب تذكرها دائماً:",
    transOutputInYourLanguage: "في لغتك الأم",
    transOutputCopyBtn: "نسخ الشرح المبسط لمشاركته مع العميل في المحادثة",
    transOutputCopiedBtn: "تم نسخ الشرح بنجاح!",

    flutterBannerTag: "📱 بوابة التحول والانتقال",
    flutterBannerSub: "منصة انتيغرافيتي وتصميم ستيتش",
    flutterBannerTitle: "جسر التحول إلى فلاتر وستيتش للموبايل",
    flutterBannerDesc: "تصدير تصاميمك إلى منصة انتيغرافيتي وبناء تطبيقات موبايل أصلية وعالية الأداء باستخدام فلاتر وتوجيهات ستيتش أصبح في غاية السهولة والمباشرة. بالأسفل مكتبات دارت كاملة التجهيز وقوالب البيانات وبروتوكولات الربط بالشبكة المتوافقة تماماً مع هذا التطبيق!",
    flutterSelectModule: "📁 اختر وحدة الكود البرمجي المراد نسخها وتصديرها:",
    flutterChecklistTitle: "قائمة التحقق لبناء المشروع بفلاتر وستيتش",
    flutterChecklist1Title: "حدود وظلال لغة ستيتش المرئية:",
    flutterChecklist1Desc: "استخدم دالة <code>neoBrutalistDecoration</code> الجاهزة بلغة دارت لإعادة بناء المظهر الكلاسيكي ذي الظلال العريضة والمسطحة على شاشات الهواتف بذكاء ودقة.",
    flutterChecklist2Title: "حفظ البيانات والتقدم محلياً:",
    flutterChecklist2Desc: "اربط منطق حفظ الملاحظات بـ localStorage لدينا بـ <code>shared_preferences</code> أو قاعدة بيانات Hive في فلاتر لضمان الحفظ الدائم.",
    flutterChecklist3Title: "المؤثرات الصوتية والصفارات التفاعلية:",
    flutterChecklist3Desc: "استخدم إضافة <code>soundpool</code> في فلاتر لتشغيل صفارات تفاعلية منخفضة التأخير تطابق المؤثرات الصوتية لدينا في متصفح الويب.",
    flutterChecklist4Title: "توفير خوادم الربط والـ API:",
    flutterChecklist4Desc: "استضف خادم Express الخاص بنا على منصة Cloud Run، وقم بتفعيل خيارات CORS، لكي يتصل تطبيق فلاتر بالمترجم الذكي وتأدية طلبات الشرح بنجاح.",
    flutterCopyLibrary: "نسخ المكتبة البرمجية الكاملة",
    flutterCopiedLibrary: "تم نسخ كود لغة دارت بنجاح!",

    interfaceLanguageSelector: "🌎 لغة الواجهة العامة:",
    footerRights: "رفيق تحديد نطاق المشروع • تم تصميمه بالاعتماد على تخطيط الباقة النابضة بالحياة لمطوري البرمجيات المحترفين."
  },
  Vietnamese: {
    appName: "Người Bạn Đồng Hành Lên Lịch Trình",
    appSubtitle: "Đón tiếp nhà sáng lập, xác định MVP rõ ràng và dịch thuật ngữ công nghệ sang các phép tương đồng dễ hiểu!",
    badgeText: "Cẩm Nang Studio",
    navPrompts: "💬 Câu Hỏi Khởi Động",
    navQuestionnaire: "📝 Khảo Sát & Tóm Tắt",
    navChecklist: "📋 Checklist Đồng Bộ",
    navTranslator: "🌎 Dịch Thuật Bình Dân",
    navFlutter: "📱 Phát Triển Flutter & Stitch",
    
    promptsBannerTag: "🗣️ BAN PHÁT CUỘC HỌP",
    promptsBannerTitle: "Bộ Câu Hỏi Khởi Động Thảo Luận",
    promptsBannerDesc: "Khi bàn luận về phần mềm tùy chỉnh với khách hàng không rành kỹ thuật, các câu hỏi khô khan như \"Bạn thích kiến trúc cơ sở dữ liệu nào?\" sẽ gây bối rối. Hãy sử dụng các thẻ câu hỏi gợi mở, ấm áp thông qua phép ẩn dụ thực tế này để thu hút câu trả lời tuyệt vời từ họ!",
    promptsCategoryTitle: "Bộ câu hỏi sẵn sàng sử dụng cho phiên thảo luận này",
    promptsCategoryObjectives: "🔑 Mục Tiêu Phiên Thảo Luận:",
    promptsExplainToClient: "CÁCH GIẢI THÍCH ĐƠN GIẢN CHO KHÁCH HÀNG:",
    promptsCopyBtn: "Sao Chép Mẫu Câu Hỏi",
    promptsCopiedBtn: "Đã Sao Chép Câu Hỏi!",
    promptsOnboardingTipTitle: "Mẹo Tiếp Cận Khách Hàng Nước Ngoài:",
    promptsOnboardingTipDesc: "Nếu khách hàng của bạn gặp khó khăn khi nói tiếng Anh, hãy để họ trả lời bằng tiếng mẹ đẻ! Bạn có thể dán trực tiếp câu trả lời của họ vào Khảo Sát Sáng Lập hoặc Dịch Thuật Bình Dân, trợ lý của chúng tôi sẽ biên dịch và tóm tắt hoàn hảo thành các yêu cầu rõ ràng.",

    questBannerTag: "📝 BẢNG KHẢO SÁT MVP",
    questBannerTitle: "Bảng Xác Định Phạm Vi Dự Án Với 5 Câu Hỏi Cốt Lõi",
    questBannerDesc: "Thay vì soạn thảo hàng chục trang đặc tả kỹ thuật phức tạp ngay từ đầu, hãy trả lời 5 câu hỏi đơn giản này để đi thẳng vào giá trị cốt lõi của phần mềm. Hãy cùng điền với khách hàng hoặc sử dụng mẫu thiết lập sẵn để xem hệ thống tự động soạn thảo tóm tắt dự án ra sao.",
    questQuickPresets: "⚡ Thiết Lập Nhanh (Nhấp để tải câu trả lời mẫu của khách hàng):",
    questFormTitle: "✍️ 5 Câu Hỏi Cơ Bản",
    questQ1: "1. Mục Tiêu Cốt Lõi (Phần mềm làm nhiệm vụ gì trong vòng 1 câu ngắn gọn?)",
    questQ2: "2. Đối Tượng Người Dùng (Ai sẽ sử dụng phần mềm này và sử dụng khi nào?)",
    questQ3: "3. Phạm Vi MVP (Top 3 tính năng bắt buộc phải có để ra mắt bản đầu tiên là gì?)",
    questQ4: "4. Yêu Cầu Kỹ Thuật (Họ có cần hệ thống đăng nhập, thanh toán trực tuyến hay tải ảnh lên không?)",
    questQ5: "5. Ngân Sách & Thời Gian (Khi nào cần ra mắt và ngân sách dự kiến khoảng bao nhiêu?)",
    questSubmitBtn: "Tạo Bản Tóm Tắt Phạm Vi Dự Án ✨",
    questBriefTitle: "Tóm Tắt Phạm Vi Dự Án",
    questBriefObjective: "🎯 Mục Tiêu Cốt Lõi:",
    questBriefTargetUsers: "👥 Người Dùng Mục Tiêu:",
    questBriefTimeline: "💰 Ràng Buộc & Thời Gian:",
    questBriefMvpTitle: "🚀 Phạm Vi Bản Phát Hành MVP (Bắt Buộc Có):",
    questBriefTechTitle: "🛠️ Đề Xuất Công Nghệ Với Phép Ẩn Dụ Thực Tế:",
    questBriefCopy: "Sao Chép Tóm Tắt Vào Clipboard",
    questBriefCopied: "Đã Sao Chép Bản Tóm Tắt!",
    questBriefShareEmail: "Chia sẻ qua Email",
    questBriefExportPdf: "Xuất ra PDF",
    questBriefReadyTitle: "Bản Tóm Tắt Sẵn Sàng Được Khởi Tạo",
    questBriefReadyDesc: "Hoàn tất 5 câu hỏi ở bên trái hoặc chọn một mẫu thử nghiệm nhanh để hiển thị ngay tóm tắt dự án trực quan, thân thiện cho khách hàng.",

    milestonesBannerTag: "📋 MỐC THỜI GIAN HỆ THỐNG",
    milestonesBannerTitle: "Cột Mốc Phát Triển Đồng Bộ Khách Hàng",
    milestonesBannerDesc: "Tránh mọi hiểu lầm đáng tiếc trong quá trình bàn giao phần mềm bằng cách sử dụng checklist từng bước này. Tích chọn các thỏa thuận đã thông qua, viết ghi chú thảo luận và lưu trực tiếp vào trình duyệt máy của bạn!",
    milestonesResetBtn: "Khởi Động Lại Toàn Bộ Checklist",
    milestonesPhase: "Giai Đoạn",
    milestonesAddNotePlaceholder: "Nhập chi tiết cuộc họp, quyết định hoặc ý kiến phản hồi của khách hàng...",
    milestonesSaveIndicator: "✔ Đã lưu ghi chú vào máy bộ nhớ cục bộ!",

    transBannerTag: "🗣️ TRỢ LÝ ĐA NGÔN NGỮ",
    transBannerTitle: "Công Cụ Đơn Giản Hóa Thuật Ngữ & Viết Tắt Công Nghệ",
    transBannerDesc: "Bạn có cảm thấy bối rối trước những cụm từ phức tạp như \"Thực thi tự động\" hay \"Mô hình RAG (Truy xuất tăng cường)\"? Hãy nhập chúng vào đây! Người bạn đồng hành thông minh sẽ dịch và diễn giải bằng câu chuyện bình dân hằng ngày giúp bạn hiểu tức thì.",
    transInputLabel: "1. Nhập hoặc dán thuật ngữ công nghệ phức tạp:",
    transInputPlaceholder: "Ví dụ: Gọi hàm trong tác nhân thông minh, tích hợp kết nối API...",
    transClickExample: "Hoặc nhấp trực tiếp vào mẫu thử nghiệm nhanh dưới đây:",
    transSelectLangLabel: "2. Dịch thuật ngữ giải thích sang tiếng mẹ đẻ:",
    transEnglishLevelLabel: "3. Độ đơn giản của tiếng Anh đích:",
    transLevelSimple: "Rất Đơn Giản (Trình độ A2)",
    transLevelMedium: "Trung Bình (Trình độ B1)",
    transSubmitBtnThinking: "Trợ lý đang suy nghĩ...",
    transSubmitBtnReady: "Đơn Giản Hóa & Giải Thích! ✨",
    transStateReadyTitle: "Trình Giải Nghĩa Đã Sẵn Sàng",
    transStateReadyDesc: "Nhập bất kỳ từ công nghệ hay AI nào ở bên trái, chọn ngôn ngữ đích và nhấp \"Đơn Giản Hóa\" để nhận ngay câu chuyện ẩn dụ thực tế sống động!",
    transStateThinkingTitle: "Đang Kết Nối Với Hệ Thống...",
    transStateThinkingDesc: "Đang bóc tách các thuật toán phức tạp thành ngôn ngữ thường nhật thân quen hằng ngày.",
    transOutputPlainWords: "Bằng Từ Ngữ Đơn Giản:",
    transOutputAnalogyStory: "Câu Chuyện Phép Ẩn Dụ",
    transOutputHowItMaps: "Tương ứng trực tiếp với kỹ thuật ra sao:",
    transOutputKeyTakeaways: "Các Điểm Cốt Lõi Cần Nhớ:",
    transOutputInYourLanguage: "Bản đối chiếu tiếng mẹ đẻ của bạn",
    transOutputCopyBtn: "Sao chép bản giải thích này (tiện trao đổi với khách hàng)",
    transOutputCopiedBtn: "Đã Sao Chép Bản Giải Thích!",

    flutterBannerTag: "📱 CẦU NỐI CHUYỂN ĐỔI DI ĐỘNG",
    flutterBannerSub: "Hệ Thống Antigravity & Stitch",
    flutterBannerTitle: "Cầu Nối Di Động Flutter & Stitch",
    flutterBannerDesc: "Xuất bản thiết kế sang nền tảng di động Antigravity và dựng ứng dụng chất lượng cao bằng Flutter & Stitch vô cùng dễ dàng. Ở bên dưới là thư viện Dart, mô hình dữ liệu, thiết lập phong cách Stitch và giao thức mạng HTTP được cấu trúc khớp hoàn toàn với dự án!",
    flutterSelectModule: "📁 Chọn mô-đun mã nguồn muốn sao chép:",
    flutterChecklistTitle: "Checklist Triển Khai Stitch & Flutter",
    flutterChecklist1Title: "Viền và Bóng Đổ Phong Cách Stitch:",
    flutterChecklist1Desc: "Sử dụng hàm trang trí <code>neoBrutalistDecoration</code> được lập trình sẵn bằng Dart để giữ nguyên vẹn thiết kế retro phẳng nổi bật lên màn hình di động.",
    flutterChecklist2Title: "Lưu Trữ Dữ Liệu Bộ Nhớ Máy:",
    flutterChecklist2Desc: "Ánh xạ cơ chế lưu ghi chú localStorage của web sang <code>shared_preferences</code> hoặc cơ sở dữ liệu nhẹ Hive trong Flutter để lưu trữ vĩnh viễn.",
    flutterChecklist3Title: "Âm Thanh Mic Interactivity:",
    flutterChecklist3Desc: "Tích hợp gói thư viện <code>soundpool</code> trong Flutter để phát âm thanh beep tương tác độ trễ cực thấp y hệt Web Audio API của web.",
    flutterChecklist4Title: "Cổng Kết Nối Gọi Mạng API:",
    flutterChecklist4Desc: "Triển khai backend Express của chúng ta lên Cloud Run, kích hoạt CORS để ứng dụng di động Flutter trực tiếp gửi lệnh dịch thuật và giải nghĩa thành công.",
    flutterCopyLibrary: "Sao Chép Toàn Bộ Mã Nguồn",
    flutterCopiedLibrary: "Mã nguồn Dart đã được sao chép thành công!",

    interfaceLanguageSelector: "🌎 Ngôn Ngữ Giao Diện:",
    footerRights: "Người Bạn Đồng Hành Lên Lịch Trình • Được hoàn thiện bằng phong cách thiết kế phẳng sinh động Vibrant Palette cho lập trình viên."
  },
  Tagalog: {
    appName: "Katuwang sa Pag-iskop ng Proyekto",
    appSubtitle: "I-onboard ang mga founder, tukuyin ang malinaw na MVP, at isalin ang jargon sa madaling analohiya!",
    badgeText: "Gabay ng Studio",
    navPrompts: "💬 Mga Tanong sa Simula",
    navQuestionnaire: "📝 Kwestyuner at Brief",
    navChecklist: "📋 Listahan ng Kasunduan",
    navTranslator: "🌎 Tagasalin para sa Layman",
    navFlutter: "📱 Pagbuo sa Flutter at Stitch",
    
    promptsBannerTag: "🗣️ TAGAPAGSIMULA NG PAGPUPULONG",
    promptsBannerTitle: "Mga Gabay sa Talakayan kasama ang Kliyente",
    promptsBannerDesc: "Kapag tinatalakay ang custom software sa isang bagong kliyente, ang mga tuyong tanong tulad ng \"Anong database architecture ang gusto mo?\" ay nagdudulot ng takot at kalituhan. Gamitin ang mga card na ito na may kasamang kwentong analohiya upang makakuha ng magagandang sagot sa kliyente habang pinananatiling simple ang lahat!",
    promptsCategoryTitle: "Mga tanong na handang gamitin para sa sesyong ito ng alignment",
    promptsCategoryObjectives: "🔑 Mga Layunin ng Sesyon:",
    promptsExplainToClient: "PAANO IPALIWANAG NANG SIMPLE SA MGA KLIYENTE:",
    promptsCopyBtn: "Kopyahin ang Template ng Tanong",
    promptsCopiedBtn: "Kopya na ang Tanong!",
    promptsOnboardingTipTitle: "Tip sa Pag-onboard para sa mga Kliyenteng Hindi Katutubong Nagsasalita ng Ingles:",
    promptsOnboardingTipDesc: "Kung nahihirapan ang iyong kliyente na magsalita ng Ingles, payagan silang sumulat o sumagot sa kanilang sariling wika! Maaari mong i-paste ang kanilang mga sagot nang direkta sa Kwestyuner para sa mga Founder o sa Tagasalin para sa Layman, at ang aming Katuwang ang magsasalin at magbubuod nito sa malinaw na patnubay ng proyekto.",

    questBannerTag: "📝 KWESTYUNER SA PAG-ISKOP",
    questBannerTitle: "Ang 5-Tanong na Lupon ng Pag-iskop para sa mga Founder",
    questBannerDesc: "Sa halip na magsulat ng mahahabang pahina ng teknikal na detalye, sagutin ang 5 simpleng tanong na ito upang makarating sa pinakapuso ng proyekto. Sagutan ito kasama ang iyong kliyente, o pumili ng mabilis na preset upang makita kung paano awtomatikong inihahanda ng system ang isang madaling basahing brief.",
    questQuickPresets: "⚡ Mabilis na Preset (I-click para i-load ang sample na sagot ng kliyente):",
    questFormTitle: "✍️ Ang Limang Pangunahing Tanong",
    questQ1: "1. Pangunahing Layunin (Ano ang ginagawa ng software sa loob ng isang pangungusap?)",
    questQ2: "2. Target na Audience (Sino ang gagamit nito, at kailan?)",
    questQ3: "3. Sakop ng MVP (Ano ang nangungunang 3 tampok na kailangang-kailangan?)",
    questQ4: "4. Teknikal na Pangangailangan (Kailangan ba nila ng login, pagbabayad, o pag-upload ng file?)",
    questQ5: "5. Limitasyon sa Badyet at Timeline (Kailan ang paglunsad at magkano ang tinantyang badyet?)",
    questSubmitBtn: "Gumawa ng Scoping Brief para sa Kliyente ✨",
    questBriefTitle: "Brief sa Pag-iskop ng Proyekto",
    questBriefObjective: "🎯 Pangunahing Layunin:",
    questBriefTargetUsers: "👥 Target na mga User:",
    questBriefTimeline: "💰 Limitasyon at Timeline:",
    questBriefMvpTitle: "🚀 Sakop ng Paglunsad ng MVP (Kailangang-kailangan):",
    questBriefTechTitle: "🛠️ Iminumungkahing Simpleng Tech Stack:",
    questBriefCopy: "Kopyahin ang Brief sa Clipboard",
    questBriefCopied: "Kopya na ang Brief!",
    questBriefShareEmail: "Ibahagi sa Email",
    questBriefExportPdf: "I-export bilang PDF",
    questBriefReadyTitle: "Brief sa Pag-iskop Handa nang Buuin",
    questBriefReadyDesc: "Kumpletuhin ang 5 tanong sa kaliwa o pumili ng interactive na preset upang makagawa agad ng malinaw na buod ng proyekto para sa kliyente.",

    milestonesBannerTag: "📋 MGA MILTON NG SISTEMA",
    milestonesBannerTitle: "Mga Milestone ng Kliyente sa Pagbuo ng Software",
    milestonesBannerDesc: "Iwasan ang hindi pagkakaunawaan sa mga kliyente at founder sa pamamagitan ng paggamit ng sunud-sunod na checklist na ito. Markahan ang mga nakumpletong kasunduan, magsulat ng mga partikular na tala sa bawat milestone, at i-save ang iyong progreso nang lokal sa iyong browser!",
    milestonesResetBtn: "I-reset ang Lahat ng Checklist",
    milestonesPhase: "Yugto",
    milestonesAddNotePlaceholder: "I-type ang mga detalye ng pagpupulong, desisyon, o komento ng kliyente dito...",
    milestonesSaveIndicator: "✔ Tala ay matagumpay na na-save nang lokal!",

    transBannerTag: "🗣️ MULTILINGWAL NA KATUWANG",
    transBannerTitle: "Ang Tagapagpagaan ng Jargon at Acronym",
    transBannerDesc: "Nakakarinig ka ba ng mga kumplikadong termino tulad ng \"Autonomous Execution\" o \"Retrieval-Augmented Generation\" at nalilito? I-type ang mga ito sa ibaba! Ang ating matalinong Katuwang ay isasalin at ipapaliwanag ang mga ito gamit ang simpleng analohiya sa araw-araw.",
    transInputLabel: "1. I-type o i-paste ang kumplikadong teknikal na termino:",
    transInputPlaceholder: "Halimbawa: Pagtawag ng function ng autonomous agent, API integration...",
    transClickExample: "O i-click ang isang halimbawa:",
    transSelectLangLabel: "2. Isalin ang paliwanag sa iyong wika:",
    transEnglishLevelLabel: "3. Target na Kasimplihan ng Ingles:",
    transLevelSimple: "Napakasimpleng Ingles (Antas A2)",
    transLevelMedium: "Katamtamang Ingles (Antas B1)",
    transSubmitBtnThinking: "Nag-iisip ang Katuwang...",
    transSubmitBtnReady: "Gawing Simple at Ipaliwanag! ✨",
    transStateReadyTitle: "Handa nang Magpaliwanag",
    transStateReadyDesc: "I-type ang anumang termino sa teknolohiya o AI sa kaliwa, piliin ang iyong wika, at i-click ang \"Gawing Simple\" upang makita ang isang madaling gabay na may kasamang masayang analohiya!",
    transStateThinkingTitle: "Kumokonekta sa Matalinong Katuwang...",
    transStateThinkingDesc: "Isinasalin ang mga kumplikadong algorithm sa mga ordinaryong salita sa araw-araw.",
    transOutputPlainWords: "Sa Simpleng Pananalita:",
    transOutputAnalogyStory: "Kwentong Analohiya",
    transOutputHowItMaps: "Paano ito nauugnay sa totoong teknolohiya:",
    transOutputKeyTakeaways: "Mga Pangunahing Punto na Dapat Tandaan:",
    transOutputInYourLanguage: "Sa iyong sariling wika",
    transOutputCopyBtn: "Kopyahin ang paliwanag para sa pakikipag-chat sa kliyente",
    transOutputCopiedBtn: "Kopya na ang Paliwanag!",

    flutterBannerTag: "📱 HUB NG PAGBIBINAYO",
    flutterBannerSub: "Antigravity at Stitch",
    flutterBannerTitle: "Tulay ng Mobile sa Flutter at Stitch",
    flutterBannerDesc: "Ang pag-export ng iyong mga disenyo sa platform ng Antigravity at paglikha ng mga de-kalidad na native mobile app gamit ang Flutter at Stitch ay napakadali. Makikita sa ibaba ang mga library sa Dart, data models, gabay sa estilo, at HTTP network protocols na tugma sa aplikasyong ito!",
    flutterSelectModule: "📁 Pumili ng Module na I-e-export:",
    flutterChecklistTitle: "Checklist sa Pagpapatupad ng Stitch at Flutter",
    flutterChecklist1Title: "Mga Border at Shadow ng Stitch:",
    flutterChecklist1Desc: "Gamitin ang ibinigay na pamamaraang neoBrutalistDecoration sa Flutter upang muling malikha ang retro na hitsura ng flat shadow nang malinis sa mobile.",
    flutterChecklist2Title: "Persistencia sa Lokal na Imbakan:",
    flutterChecklist2Desc: "I-map ang ating lohika ng localStorage ng web nang direkta sa shared_preferences o Hive database sa Flutter upang mapanatili ang progreso.",
    flutterChecklist3Title: "Mga Sintetikong Sound Effect:",
    flutterChecklist3Desc: "Gamitin ang soundpool plugin sa Flutter upang magpatugtog ng mga low-latency na beep na tumutugma sa Web Audio API synthesizer ng web.",
    flutterChecklist4Title: "Endpoint ng Network ng API:",
    flutterChecklist4Desc: "I-host ang ating Express server sa Cloud Run o isang dedikadong URL, i-configure ang CORS, at hayaan ang Flutter app na gamitin ang mga simpleng paliwanag.",
    flutterCopyLibrary: "Kopyahin ang Buong Library",
    flutterCopiedLibrary: "Kopya na ang Dart Code!",

    interfaceLanguageSelector: "🌎 Wikang Pandaigdig ng App:",
    footerRights: "Katuwang sa Pag-iskop ng Proyekto • Dinisenyo sa ilalim ng makulay na paleta para sa mga tagabuo ng software."
  },
  Hindi: {
    appName: "ग्राहक प्रोजेक्ट स्कोपिंग सहायक",
    appSubtitle: "गैर-तकनीकी संस्थापकों को ऑनबोर्ड करें, स्पष्ट MVP सुविधाएँ तय करें, और जटिल तकनीकी शब्दों का सरल जीवन उदाहरणों में अनुवाद करें!",
    badgeText: "स्टूडियो गाइड",
    navPrompts: "💬 चर्चा शुरू करने के प्रश्न",
    navQuestionnaire: "📝 स्कोपिंग प्रश्नावली एवं ब्रीफ",
    navChecklist: "📋 संरेखण चेकलिस्ट",
    navTranslator: "🌎 लेमैन तकनीकी अनुवादक",
    navFlutter: "📱 फ़्लटर और स्टिच देव",
    
    promptsBannerTag: "🗣️ मीटिंग कनवर्टर",
    promptsBannerTitle: "ग्राहक चर्चा शुरू करने के प्रश्न कार्ड",
    promptsBannerDesc: "गैर-तकनीकी ग्राहकों के साथ कस्टम सॉफ़्टवेयर पर चर्चा करते समय, \"आपको कौन सा डेटाबेस आर्किटेक्चर पसंद है?\" जैसे शुष्क प्रश्न घबराहट और भ्रम पैदा करते हैं। चर्चा को आनंददायक और सरल रखते हुए ग्राहकों से शानदार प्रतिक्रिया प्राप्त करने के लिए इन सरल जीवन रूपकों और विश्लेषण कार्ड का उपयोग करें!",
    promptsCategoryTitle: "इस संरेखण बैठक के लिए तैयार-उपयोग प्रश्न सूची",
    promptsCategoryObjectives: "🔑 सत्र के मुख्य उद्देश्य:",
    promptsExplainToClient: "ग्राहकों को सरल शब्दों में कैसे समझाएं:",
    promptsCopyBtn: "प्रश्न टेम्पलेट कॉपी करें",
    promptsCopiedBtn: "प्रश्न कॉपी हो गया!",
    promptsOnboardingTipTitle: "गैर-देशी ग्राहकों के लिए ऑनबोर्डिंग टिप:",
    promptsOnboardingTipDesc: "यदि आपके ग्राहक को अंग्रेजी बोलने में कठिनाई होती है, तो उन्हें अपनी मातृभाषा में लिखने या उत्तर देने दें! आप उनके उत्तर सीधे प्रश्नावली या अनुवादक में पेस्ट कर सकते हैं, और हमारा सहायक उन्हें आसान तकनीकी निर्देशों में बदल देगा।",

    questBannerTag: "📝 प्रोजेक्ट स्कोप प्रश्नावली",
    questBannerTitle: "संस्थापकों के लिए 5-प्रश्न स्कोपिंग बोर्ड",
    questBannerDesc: "दर्जनों जटिल तकनीकी विशिष्टताओं को लिखने के बजाय, परियोजना के मूल मूल्य तक पहुंचने के लिए इन 5 सरल प्रश्नों के उत्तर दें। अपने ग्राहक के साथ मिलकर इन्हें भरें, या स्वचालित रूप से एक सुंदर सारांश देखने के लिए प्रीसेट उदाहरण चुनें।",
    questQuickPresets: "⚡ त्वरित प्रीसेट (नमूना ग्राहक उत्तर लोड करने के लिए क्लिक करें):",
    questFormTitle: "✍️ पांच बुनियादी प्रश्न",
    questQ1: "1. मुख्य लक्ष्य (सॉफ़्टवेयर केवल 1 संक्षिप्त वाक्य में क्या करता है?)",
    questQ2: "2. लक्षित दर्शक (इस सॉफ़्टवेयर का उपयोग कौन और कब करेगा?)",
    questQ3: "3. एमवीपी स्कोप (शीर्ष 3 'होनी ही चाहिए' सुविधाएँ क्या हैं?)",
    questQ4: "4. तकनीकी आवश्यकताएं (क्या उन्हें लॉगिन, ऑनलाइन भुगतान या फ़ाइल अपलोड की आवश्यकता है?)",
    questQ5: "5. बजट और समय सीमा (अनुमानित बजट क्या है और लॉन्च कब करना है?)",
    questSubmitBtn: "प्रोजेक्ट स्कोपिंग सारांश जनरेट करें ✨",
    questBriefTitle: "प्रोजेक्ट स्कोपिंग ब्रीफ",
    questBriefObjective: "🎯 मुख्य उद्देश्य:",
    questBriefTargetUsers: "👥 लक्षित उपयोगकर्ता:",
    questBriefTimeline: "💰 समय सीमा और अनुमानित बजट:",
    questBriefMvpTitle: "🚀 एमवीपी लॉन्च स्कोप (अनिवार्य आवश्यकताएं):",
    questBriefTechTitle: "🛠️ अनुशंसित सरल तकनीक स्टैक (जीवन उपमाओं के साथ):",
    questBriefCopy: "ब्रीफ को क्लिपबोर्ड पर कॉपी करें",
    questBriefCopied: "ब्रीफ सफलतापूर्वक कॉपी हो गया!",
    questBriefShareEmail: "ईमेल के माध्यम से साझा करें",
    questBriefExportPdf: "PDF के रूप में निर्यात करें",
    questBriefReadyTitle: "ब्रीफ जनरेशन के लिए तैयार",
    questBriefReadyDesc: "प्रोजेक्ट का एक सरल अवलोकन तुरंत देखने के लिए बाईं ओर के 5 प्रश्नों को पूरा करें या कोई एक प्रीसेट उदाहरण चुनें।",

    milestonesBannerTag: "📋 सिस्टम मील के पत्थर",
    milestonesBannerTitle: "सॉफ़्टवेयर विकास ग्राहक मील के पत्थर",
    milestonesBannerDesc: "इस चरण-दर-चरण चेकलिस्ट का उपयोग करके ग्राहकों के साथ किसी भी गलतफहमी से बचें। स्वीकृत समझौतों को चिह्नित करें, प्रत्येक मील के पत्थर पर सीधे चर्चा विवरण लिखें और अपनी प्रगति को ब्राउज़र के लोकल स्टोरेज में स्वचालित रूप से सहेजें!",
    milestonesResetBtn: "सभी चेकलिस्ट रीसेट करें",
    milestonesPhase: "चरण",
    milestonesAddNotePlaceholder: "मीटिंग विवरण, निर्णय या ग्राहक की प्रतिक्रिया यहाँ लिखें...",
    milestonesSaveIndicator: "✔ टिप्पणी सफलतापूर्वक स्थानीय रूप से सहेजी गई!",

    transBannerTag: "🗣️ बहुभाषी तकनीकी सहायक",
    transBannerTitle: "तकनीकी शब्दों और संक्षिप्ताक्षरों का सरलीकरण",
    transBannerDesc: "क्या आप \"ऑटोनॉमस एग्जीक्यूशन\" या \"RAG\" जैसे जटिल शब्दों को सुनकर भ्रमित हो जाते हैं? उन्हें नीचे लिखें! हमारा स्मार्ट सहायक उन्हें दैनिक जीवन के रूपकों की कहानियों में सरल बनाकर समझाएगा ताकि आप आसानी से समझ सकें।",
    transInputLabel: "1. जटिल तकनीकी शब्द यहाँ लिखें या पेस्ट करें:",
    transInputPlaceholder: "उदाहरण: स्वायत्त एजेंट फ़ंक्शन कॉलिंग, एपीआई एकीकरण...",
    transClickExample: "या त्वरित परीक्षण के लिए नीचे दिए गए उदाहरण पर क्लिक करें:",
    transSelectLangLabel: "2. स्पष्टीकरण का अपनी मातृभाषा में अनुवाद करें:",
    transEnglishLevelLabel: "3. लक्ष्य अंग्रेजी की सरलता का स्तर:",
    transLevelSimple: "बहुत सरल (स्तर A2)",
    transLevelMedium: "मध्यम समझने योग्य (स्तर B1)",
    transSubmitBtnThinking: "सहायक सोच रहा है...",
    transSubmitBtnReady: "सरल बनाएं और समझाएं! ✨",
    transStateReadyTitle: "अनुवादक समझाने के लिए तैयार है",
    transStateReadyDesc: "बाईं ओर कोई भी तकनीकी या एआई शब्द लिखें, अपनी भाषा चुनें, और दैनिक जीवन की उपमाओं के साथ एक आसान स्पष्टीकरण देखने के लिए \"सरल बनाएं\" पर क्लिक करें!",
    transStateThinkingTitle: "स्मार्ट सहायक से जुड़ रहा है...",
    transStateThinkingDesc: "जटिल एल्गोरिदम और तकनीकी शब्दों को दैनिक जीवन की कहानियों में परिवर्तित किया जा रहा है।",
    transOutputPlainWords: "सरल शब्दों में स्पष्टीकरण:",
    transOutputAnalogyStory: "दैनिक जीवन रूपक कहानी",
    transOutputHowItMaps: "वास्तविक तकनीकी कामकाज से इसका संबंध:",
    transOutputKeyTakeaways: "याद रखने योग्य मुख्य बातें:",
    transOutputInYourLanguage: "आपकी मातृभाषा में अनुवाद",
    transOutputCopyBtn: "ग्राहक चर्चा के लिए इस स्पष्टीकरण को कॉपी करें",
    transOutputCopiedBtn: "स्पष्टीकरण सफलतापूर्वक कॉपी हो गया!",

    flutterBannerTag: "📱 मोबाइल संक्रमण केंद्र",
    flutterBannerSub: "एंटीग्रेविटी और स्टिच डिज़ाइन",
    flutterBannerTitle: "फ़्लटर और स्टिच मोबाइल संक्रमण ब्रिज",
    flutterBannerDesc: "अपने डिज़ाइनों को एंटीग्रेविटी प्लेटफ़ॉर्म पर निर्यात करना और फ़्लटर और स्टिच डिज़ाइन दिशानिर्देशों का उपयोग करके सुंदर मूल मोबाइल ऐप बनाना बेहद आसान है। इस एप्लिकेशन के नियमों, डेटा और शैली के अनुकूल पूरी तरह से तैयार डार्ट लाइब्रेरी कोड नीचे दिया गया है!",
    flutterSelectModule: "📁 निर्यात करने के लिए कोड मॉड्यूल चुनें:",
    flutterChecklistTitle: "स्टिच और फ़्लटर कार्यान्वयन चेकलिस्ट",
    flutterChecklist1Title: "स्टिच बॉर्डर और शैडो प्रभाव:",
    flutterChecklist1Desc: "मोबाइल स्क्रीन पर फ्लैट शैडो लुक को सहेजने के लिए डार्ट में तैयार किए गए <code>neoBrutalistDecoration</code> डेकोरेशन फ़ंक्शन का उपयोग करें।",
    flutterChecklist2Title: "स्थानीय संग्रहण और प्रगति सहेजना:",
    flutterChecklist2Desc: "प्रगति को सहेजने के लिए वेब के localStorage को फ़्लटर के <code>shared_preferences</code> या Hive डेटाबेस में मैप करें।",
    flutterChecklist3Title: "इंटरएक्टिव ध्वनि प्रभाव:",
    flutterChecklist3Desc: "फ़्लटर में <code>soundpool</code> पैकेज का उपयोग करें ताकि लो-लेटेंसी बीप ध्वनि प्रतिक्रियाएं वेब ऑडियो एपीआई की तरह मोबाइल में चल सकें।",
    flutterChecklist4Title: "एपीआई नेटवर्क एंडपॉइंट सेट करना:",
    flutterChecklist4Desc: "हमारे एक्सप्रेस बैकएंड को क्लाउड रन पर होस्ट करें, CORS चालू करें, ताकि फ़्लटर ऐप सीधे अनुवाद और सरलीकरण अनुरोध भेज सके।",
    flutterCopyLibrary: "पूरी लाइब्रेरी कॉपी करें",
    flutterCopiedLibrary: "डार्ट कोड सफलतापूर्वक कॉपी हो गया!",

    interfaceLanguageSelector: "🌎 ऐप की मुख्य भाषा:",
    footerRights: "ग्राहक प्रोजेक्ट स्कोपिंग सहायक • सॉफ़्टवेयर डेवलपर्स के लिए जीवंत वाइब्रेंट पैलेट स्टाइल में निर्मित।"
  },
  Korean: {
    appName: "고객 요구사항 조율 도구",
    appSubtitle: "창업자를 온보딩하고, 명확한 MVP를 정의하며, 어려운 기술 용어를 쉬운 일상 비유로 번역합니다!",
    badgeText: "스튜디오 가이드",
    navPrompts: "💬 소통용 시작 질문",
    navQuestionnaire: "📝 요구사항 질문 및 브리프",
    navChecklist: "📋 진척 조율 체크리스트",
    navTranslator: "🌎 비전문가용 기술 번역기",
    navFlutter: "📱 Flutter & Stitch 전환",
    
    promptsBannerTag: "🗣️ 회의 시작 도구",
    promptsBannerTitle: "고객 대화 유도용 질문 카드",
    promptsBannerDesc: "비기술자인 고객에게 \"어떤 데이터베이스 아키텍처를 선호하십니까?\" 같은 딱딱한 질문을 던지면 혼란과 두려움을 유발합니다. 일상 속 친숙한 비유를 담은 대화용 질문 카드를 통해 복잡한 사양을 쉽게 풀어가며 최고의 아이디어를 이끌어내세요!",
    promptsCategoryTitle: "이 조율 세션에서 바로 사용할 수 있는 질문 목록",
    promptsCategoryObjectives: "🔑 세션 달성 목표:",
    promptsExplainToClient: "고객에게 전달하는 '쉬운 설명 가이드':",
    promptsCopyBtn: "질문 템플릿 복사",
    promptsCopiedBtn: "질문이 복사되었습니다!",
    promptsOnboardingTipTitle: "영어권 외 고객과 대화 시 팁:",
    promptsOnboardingTipDesc: "만약 고객이 영어로 세세히 설명하기 어려워한다면, 모국어로 답변을 작성하도록 하세요! 그 답변을 '창업자 질문지'나 '기술 번역기'에 그대로 붙여넣기만 하면, 본 도구가 깔끔한 시스템 사양 문서로 알아서 번역하고 정리해 줍니다.",

    questBannerTag: "📝 요구사항 스코프 질문",
    questBannerTitle: "창업자용 요구사항 정의 '기본 5문항' 보드",
    questBannerDesc: "수십 페이지에 달하는 복잡한 기술 사양서를 작성하는 대신, 이 간단한 5가지 질문에 답하는 것만으로 프로젝트의 본질을 완벽히 포착할 수 있습니다. 고객과 함께 작성하거나 프리셋 예제를 선택하여 프로젝트 요구사항 브리프가 자동으로 생성되는 방식을 확인해 보세요.",
    questQuickPresets: "⚡ 빠른 프리셋 (클릭하여 샘플 고객 답변 로드):",
    questFormTitle: "✍️ 핵심 5가지 질문",
    questQ1: "1. 핵심 목표 (이 앱이 한 문장으로 무엇을 하는 도구인가요?)",
    questQ2: "2. 대상 타겟 (누가 언제 어떤 상황에서 주로 사용하나요?)",
    questQ3: "3. MVP 범위 (처음에 반드시 들어가야 하는 상위 3가지 필수 기능은?)",
    questQ4: "4. 기술적 필요성 (로그인, 신용카드 결제, 이미지 및 파일 업로드가 필요한가요?)",
    questQ5: "5. 예산 및 일정 제약 (언제쯤 출시를 계획하며 예산 한도는 어느 정도인가요?)",
    questSubmitBtn: "프로젝트 요구사항 브리프 생성 ✨",
    questBriefTitle: "프로젝트 요구사항 브리프",
    questBriefObjective: "🎯 핵심 목표:",
    questBriefTargetUsers: "👥 대상 타겟:",
    questBriefTimeline: "💰 일정 및 예산:",
    questBriefMvpTitle: "🚀 MVP 출시 시 기능 범위 (필수 요건):",
    questBriefTechTitle: "🛠️ 추천하는 심플한 기술 스택 (비유 설명 포함):",
    questBriefCopy: "요구사항 브리프 복사",
    questBriefCopied: "요구사항 브리프가 복사되었습니다!",
    questBriefShareEmail: "이메일로 공유",
    questBriefExportPdf: "PDF로 내보내기",
    questBriefReadyTitle: "브리프 생성 준비 완료",
    questBriefReadyDesc: "왼쪽의 5가지 질문에 입력하거나 프리셋 예제를 선택하면, 고객 맞춤형 브리프 요약안이 즉시 생성됩니다.",

    milestonesBannerTag: "📋 시스템 마일스톤",
    milestonesBannerTitle: "소프트웨어 개발 고객 조율 마일스톤",
    milestonesBannerDesc: "체크리스트를 활용하여 개발 단계별 오해와 커뮤니케이션 오류를 방지해 보세요. 합의된 항목에 체크하고, 회의 결정 사항 및 고객의 의견을 즉시 메모해 두세요. 메모는 브라우저 로컬 저장소에 자동으로 안전하게 보관됩니다!",
    milestonesResetBtn: "체크리스트 전체 초기화",
    milestonesPhase: "단계",
    milestonesAddNotePlaceholder: "회의 상세 사항, 결정 사항 또는 고객의 요구 피드백을 입력...",
    milestonesSaveIndicator: "✔ 메모가 로컬에 자동 저장되었습니다!",

    transBannerTag: "🗣️ 다국어 IT 보조도구",
    transBannerTitle: "IT 용어 및 약어 일상 비유 번역기",
    transBannerDesc: "「자율형 에이전트(Autonomous Execution)」나 「RAG(검색 증강 생성)」 같은 어려운 기술 용어 때문에 당황하셨나요? 아래에 기술 용어를 입력하세요! 스마트 어시스턴트가 이해하기 쉬운 일상 비유 스토리로 번역하고 명쾌하게 해설합니다.",
    transInputLabel: "1. 어려운 기술 용어를 입력하거나 붙여넣으세요:",
    transInputPlaceholder: "예: 자율 에이전트의 함수 호출, API 연동, 비동기 통신...",
    transClickExample: "또는 아래의 예시를 직접 클릭해 체험해 보세요:",
    transSelectLangLabel: "2. 번역 해설을 제공받을 언어 선택:",
    transEnglishLevelLabel: "3. 해설에 사용할 영어의 난이도:",
    transLevelSimple: "매우 쉬운 영어 (A2 레벨 상당)",
    transLevelMedium: "보통의 영어 (B1 레벨 상당)",
    transSubmitBtnThinking: "어시스턴트가 생각 중...",
    transSubmitBtnReady: "알기 쉽게 해설하기! ✨",
    transStateReadyTitle: "기술 용어 해설 준비 완료",
    transStateReadyDesc: "왼쪽에 어려운 AI 및 기술 단어를 입력하고 언어를 선택한 다음 \"해설하기\"를 누르면, 일상 속 예시를 듬뿍 담은 친근한 용어 해설이 제공됩니다.",
    transStateThinkingTitle: "스마트 어시스턴트에 연결하는 중...",
    transStateThinkingDesc: "복잡한 알고리즘 단어를 친근하고 평범한 일상의 언어로 풀어내고 있습니다.",
    transOutputPlainWords: "한 줄 요약 (쉬운 단어):",
    transOutputAnalogyStory: "일상 비유 스토리",
    transOutputHowItMaps: "실제 기술 작동 원리와의 대응 관계:",
    transOutputKeyTakeaways: "기억해 두면 유익한 핵심 요점:",
    transOutputInYourLanguage: "고객님의 모국어 대비 확인",
    transOutputCopyBtn: "이 해설을 복사하기 (고객과의 소통 및 설명에 매우 편리합니다)",
    transOutputCopiedBtn: "해설이 복사되었습니다!",

    flutterBannerTag: "📱 모바일 전환 허브",
    flutterBannerSub: "Antigravity & Stitch 디자인",
    flutterBannerTitle: "Flutter & Stitch 모바일 전환 브릿지",
    flutterBannerDesc: "프로토타입을 모바일 실제 작동을 위해 Antigravity 플랫폼으로 내보내고, Flutter와 Stitch 디자인 표준을 사용하여 완벽한 모바일 네이티브 앱을 구축하는 것은 아주 쉽습니다. 아래에 비즈니스 규칙 및 디자인 시스템 사양에 맞춘 Dart 모델 클래스와 API 통신 라이브러리가 완전히 생성되어 제공됩니다!",
    flutterSelectModule: "📁 내보낼 소스 코드 모듈 선택:",
    flutterChecklistTitle: "Stitch & Flutter 구현 체크리스트",
    flutterChecklist1Title: "Stitch 프레임 및 섀도우 효과:",
    flutterChecklist1Desc: "모바일 화면에 당사 전용 복고풍 뉴브루탈리즘 스타일의 두꺼운 평면 그림자를 완벽히 재현하기 위해 다트에 구성된 <code>neoBrutalistDecoration</code> 데코레이션 함수를 활용하세요.",
    flutterChecklist2Title: "로컬 데이터 영속화 처리:",
    flutterChecklist2Desc: "웹 로컬 스토리지 메모 저장 로직을 Flutter 표준의 <code>shared_preferences</code> 또는 Hive 가벼운 데이터베이스로 매핑하여 진척을 영구적으로 유지시킵니다.",
    flutterChecklist3Title: "마이크로 비프 사운드 효과:",
    flutterChecklist3Desc: "Flutter에서 <code>soundpool</code> 패키지를 적용하여 웹 브라우저 standard Web Audio API 신디사이저와 유사한 초저지연 전자 비프 사운드 피드백을 모바일 기기에 구현합니다.",
    flutterChecklist4Title: "API 통신 요청 엔드포인트 설정:",
    flutterChecklist4Desc: "Express 백엔드를 Cloud Run 등에 호스팅하고 CORS 통신을 허용해, Flutter 앱 클라이언트에서 다이렉트로 기술 번역 해설 API를 전송할 수 있도록 연결합니다.",
    flutterCopyLibrary: "전체 코드 라이브러리 복사",
    flutterCopiedLibrary: "Dart 소스 코드가 복사되었습니다!",

    interfaceLanguageSelector: "🌎 앱 전체 사용 언어:",
    footerRights: "고객 요구사항 조율 도구 • 크리에이터를 위한 강렬하고 조화로운 'Vibrant Palette' 플랫 UI 디자인 탑재."
  }
};
